const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'client', 'src', 'context', 'LanguageContext.jsx');
let content = fs.readFileSync(filePath, 'utf8');

const enKeys = `
    // New Dashboard & Checkout Keys
    hello: 'Hello',
    healthHub: 'Health Hub',
    medicalOverview: 'Your medical overview & quick actions.',
    lastActivity: 'Last Activity',
    syncing: 'Syncing...',
    updatedNow: 'Updated Now',
    loadingDashboard: 'Loading Dashboard...',
    syncingSecureClinicalData: 'Syncing Secure Clinical Data',
    liveFulfillmentSync: 'Live Fulfillment Sync',
    activeOrders: 'Active Orders',
    currentDeliveryStatus: 'Your current delivery status',
    noActiveOrders: 'No active orders right now',
    viewAllOrdersCount: 'View All Orders ({count})',
    quickAccess: 'Quick Access',
    optimizedForYou: 'Optimized for you',
    totalOrders: 'Total Orders',
    activeDelivery: 'Active Delivery',
    appointments: 'Appointments',
    uploadPrescription: 'Upload Prescription',
    bookDoctor: 'Book Doctor',
    openWallet: 'Open Wallet',
    orderAgain: 'Order Again',
    uploadPrescriptionDesc: 'Upload your prescription',
    bookDoctorDesc: 'Book a doctor appointment',
    openWalletDesc: 'View your wallet balance',
    orderAgainDesc: 'Reorder previous medicines',
    availableMedicines: 'Available Medicines',
    inStockNow: 'In stock now',
    activeDoctors: 'Active Doctors',
    availableSpecialists: 'Available specialists',
    transactions: 'Transactions',
    history: 'History',
    noTransactionsYet: 'No transactions yet',
    paymentHistoryAppear: 'Your payment history will appear here',
    myOrdersTitle: 'My Orders',
    trackManageOrders: 'Track and manage your orders',
    searchOrdersPlaceholder: 'Search by order ID or pharmacy...',
    protocolId: 'Protocol ID',
    syncDate: 'Sync Date',
    sourceNode: 'Source Node',
    payloadMeta: 'Payload Meta',
    transmissionTimeline: 'Transmission Timeline',
    trackLink: 'Track Link',
    invertInvoice: 'Invert Invoice',
    nullEnclaveDetected: 'Null Enclave Detected',
    noLogisticsFound: 'No {status} logistics synchronizations found in the clinical registry.',
    initializeProcurement: 'Initialize Procurement',
    estimatedDelivery: 'Estimated Delivery',
    itemList: 'Item List',
    modulesCount: '{count} Modules',
    qtyCount: 'Qty: {qty}',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    deliveryAddress: 'Delivery Address',
    paymentMethod: 'Payment Method',
    payNow: 'PAY NOW',
    processing: 'PROCESSING...',
    secureEncryption: 'Secure 256-bit AES Encryption Node',
    backToCart: 'Back to Cart',
    orLoginWith: 'OR LOGIN WITH',
    newHere: 'New here?',
    createAccount: 'Create Account',
    demoAccounts: 'Demo Accounts',
    continueBrowsing: 'Continue browsing without an account',
`;

const taKeys = `
    // New Dashboard & Checkout Keys (Tamil)
    hello: 'வணக்கம்',
    healthHub: 'சுகாதார மையம்',
    medicalOverview: 'உங்கள் மருத்துவ கண்ணோட்டம் மற்றும் விரைவான செயல்கள்.',
    lastActivity: 'கடைசி செயல்பாடு',
    syncing: 'ஒத்திசைக்கப்படுகிறது...',
    updatedNow: 'இப்போது புதுப்பிக்கப்பட்டது',
    loadingDashboard: 'டேஷ்போர்டு ஏற்றப்படுகிறது...',
    syncingSecureClinicalData: 'பாதுகாப்பான மருத்துவத் தரவை ஒத்திசைக்கிறது',
    liveFulfillmentSync: 'நேரடி விநியோக ஒத்திசைவு',
    activeOrders: 'செயலில் உள்ள ஆர்டர்கள்',
    currentDeliveryStatus: 'உங்கள் தற்போதைய விநியோக நிலை',
    noActiveOrders: 'இப்போது செயலில் உள்ள ஆர்டர்கள் இல்லை',
    viewAllOrdersCount: 'அனைத்து ஆர்டர்களையும் காண்க ({count})',
    quickAccess: 'விரைவான அணுகல்',
    optimizedForYou: 'உங்களுக்காக மேம்படுத்தப்பட்டது',
    totalOrders: 'மொத்த ஆர்டர்கள்',
    activeDelivery: 'செயலில் உள்ள விநியோகம்',
    appointments: 'சந்திப்புகள்',
    uploadPrescription: 'மருந்துச்சீட்டைப் பதிவேற்றவும்',
    bookDoctor: 'மருத்துவரை முன்பதிவு செய்யவும்',
    openWallet: 'வாலட்டைத் திறக்கவும்',
    orderAgain: 'மீண்டும் ஆர்டர் செய்யவும்',
    uploadPrescriptionDesc: 'உங்கள் மருந்துச்சீட்டைப் பதிவேற்றவும்',
    bookDoctorDesc: 'மருத்துவர் சந்திப்பை முன்பதிவு செய்யவும்',
    openWalletDesc: 'உங்கள் வாலட் இருப்பைக் காண்க',
    orderAgainDesc: 'முந்தைய மருந்துகளை மீண்டும் ஆர்டர் செய்யவும்',
    availableMedicines: 'கிடைக்கும் மருந்துகள்',
    inStockNow: 'இப்போது இருப்பில் உள்ளது',
    activeDoctors: 'செயலில் உள்ள மருத்துவர்கள்',
    availableSpecialists: 'கிடைக்கும் நிபுணர்கள்',
    transactions: 'பரிவர்த்தனைகள்',
    history: 'வரலாறு',
    noTransactionsYet: 'இன்னும் பரிவர்த்தனைகள் இல்லை',
    paymentHistoryAppear: 'உங்கள் கட்டண வரலாறு இங்கே தோன்றும்',
    myOrdersTitle: 'எனது ஆர்டர்கள்',
    trackManageOrders: 'ஆர்டர்களைக் கண்காணித்து நிர்வகிக்கவும்',
    searchOrdersPlaceholder: 'ஆர்டர் ஐடி அல்லது மருந்தகம் மூலம் தேடுங்கள்...',
    protocolId: 'நெறிமுறை ஐடி',
    syncDate: 'ஒத்திசைவு தேதி',
    sourceNode: 'மூல முனை',
    payloadMeta: 'பேலோட் மெட்டா',
    transmissionTimeline: 'பரிமாற்ற காலவரிசை',
    trackLink: 'ட்ராக் இணைப்பு',
    invertInvoice: 'இன்வாய்ஸ்',
    nullEnclaveDetected: 'தரவு எதுவும் இல்லை',
    noLogisticsFound: 'மருத்துவ பதிவேட்டில் {status} தளவாட ஒத்திசைவுகள் எதுவும் இல்லை.',
    initializeProcurement: 'ஆர்டர் தொடங்கவும்',
    estimatedDelivery: 'மதிப்பிடப்பட்ட விநியோகம்',
    itemList: 'பொருட்களின் பட்டியல்',
    modulesCount: '{count} தொகுதிகள்',
    qtyCount: 'அளவு: {qty}',
    subtotal: 'துணை மொத்தம்',
    deliveryFee: 'விநியோக கட்டணம்',
    discount: 'தள்ளுபடி',
    grandTotal: 'மொத்த தொகை',
    deliveryAddress: 'விநியோக முகவரி',
    paymentMethod: 'கட்டண முறை',
    payNow: 'இப்போது செலுத்தவும்',
    processing: 'செயலாக்கப்படுகிறது...',
    secureEncryption: 'பாதுகாப்பான 256-பிட் ஏஇஎஸ் குறியாக்க முனை',
    backToCart: 'கூடைக்குத் திரும்பவும்',
    orLoginWith: 'அல்லது இதைப் பயன்படுத்தி உள்நுழையவும்',
    newHere: 'புதியவரா?',
    createAccount: 'கணக்கை உருவாக்கு',
    demoAccounts: 'டெமோ கணக்குகள்',
    continueBrowsing: 'கணக்கு இல்லாமல் உலாவலைத் தொடரவும்',
`;

// Insert en keys before the first "  },"
const enEndIdx = content.indexOf('  },');
if (enEndIdx !== -1) {
    content = content.substring(0, enEndIdx) + enKeys + content.substring(enEndIdx);
}

// Insert ta keys before the last "  }" of the translations object
const translationsEndIdx = content.lastIndexOf('  }');
if (translationsEndIdx !== -1) {
    content = content.substring(0, translationsEndIdx) + taKeys + content.substring(translationsEndIdx);
}

fs.writeFileSync(filePath, content);
console.log('Successfully updated LanguageContext.jsx with new keys.');
