import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navbar & Layout
    heroTitle: 'Order Medicines Online Today',
    heroSubtitle: 'Karaikal Medicine Hub.',
    heroDesc: 'Order medicines from trusted local pharmacies. Fast delivery to your door across Karaikal, Nagore, and Poompuhar.',
    orderNow: 'Start Shopping',
    findNear: 'Find Shops',
    locate: 'Find',
    karaikal: 'Karaikal',
    deliverTo: 'Deliver to',
    activeNodes: '12 Shops Open',
    nodesOnline: 'Verified & Open',
    shoppingCart: 'Shopping Cart',
    myInventory: 'My Cart',
    selectedItems: 'Selected Items',
    clearManifestRegistry: 'Clear All Items',
    deliveryNotes: 'Delivery Instructions',
    deliveryNotesInstructions: 'Add notes for the delivery person (e.g. building name, floor, or landmark).',
    architecturalIntegrity: 'Secure & Verified',
    integrityVerificationDesc: 'Every order is checked by licensed pharmacists for safety.',
    cartEmptyTitle: 'Your cart is empty',
    cartEmptyDesc: 'Looks like you haven\'t added any medicines yet.',
    browseInventory: 'Browse Medicines',
    home: 'Home',
    medicines: 'Buy',
    pharmacies: 'Pharmacies',
    doctors: 'Doctor',
    teleconsultation: 'Doctor',
    prescriptions: 'Prescriptions',
    myOrders: 'Orders',
    about: 'About',
    aboutUs: 'About',
    contact: 'Contact Us',
    offers: 'Discounts',
    blog: 'Health Tips',
    notifications: 'Notifications',
    myWallet: 'My Wallet',
    helpSupport: 'Help & Support',
    logout: 'Sign Out',
    logoutSystem: 'Log Out',
    visitor: 'Guest',
    login: 'Log In',
    register: 'Sign Up',
    cart: 'My Cart',
    search: 'Search',
    alerts: 'Notifications',
    profile: 'My Profile',
    
    // Roles
    customer: 'Customer',
    pharmacist: 'Pharmacist',
    delivery: 'Delivery Partner',
    admin: 'Administrator',
    enclave: 'Enclave',
    
    // Statuses
    pending: 'Pending',
    verified: 'Verified',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    placed: 'Placed',
    confirmed: 'Confirmed',
    
    // Stats & Categories
    statsPharmacies: 'Trusted Pharmacies',
    statsMedicines: 'Medicines Available',
    statsDelivery: 'Fastest Delivery',
    statsCustomers: 'Happy Customers',
    shopCategory: 'Shop by Category',
    shopCategoryTitleMain: 'Categories',
    shopCategoryTitleSub: 'Shop',
    exploreCatalog: 'View All Medicines',
    browseCuratedClusters: 'Browse medicines and health products for your family.',
    accessNodes: 'See Shops',
    
    // Popular Meds & Pharmacies
    popularMeds: 'Best Selling Medicines',
    liveSync: 'Live Order Updates',
    districtNode: 'Shop is Open',
    offlineNode: 'Shop is Closed',
    verifiedHealthArchitecture: 'Trusted healthcare for every home in Karaikal.',
    initializingTelemetry: 'Loading...',
    districtNetwork: 'Local Pharmacy Network',
    pharmaciesNear: 'Pharmacies Near You',
    verifiedLicensedPharmacies: 'Verified and licensed pharmacies in Karaikal.',
    openNow: 'Open Now',
    freeDel: 'Free Delivery',
    nodeRef: 'License ID',
    nodeActive: 'ACTIVE',
    
    // Home Sections C
    vaccinesAvailable: 'Available Vaccines',
    dose: 'Dose',
    priceCard: 'Price',
    storeLocation: 'Shop Location',
    available: 'In Stock',
    outOfStock: 'Out of Stock',
    howItWorks: 'How it Works',
    seamlessLogistics: 'Easy Ordering',
    districtArchitecture: 'How to order medicines from MediPharm in 4 simple steps.',
    searchMedicineTitle: 'Find your medicine',
    searchMedicineDesc: 'Search all local pharmacies for your medicine.',
    choosePharmacyTitle: 'Pick a pharmacy',
    choosePharmacyDesc: 'Select from 8 verified local pharmacies.',
    payYourWayTitle: 'Easy Payment',
    payYourWayDesc: 'Secure and encrypted payment options.',
    liveGpsTitle: 'Track Delivery',
    liveGpsDesc: 'See your delivery on a live map.',
    consultOnline: 'Talk to a Doctor',
    speakWithDoctors: 'Speak with a doctor in 10 minutes from your home.',
    viewAllDoctors: 'See All Doctors',
    gpsTrackingTitle: 'Track your order live.',
    gpsTrackingDesc: 'See where your delivery driver is in real-time on the map.',
    riderTelemetry: 'Driver is on the way',
    pharmacyVerification: 'Verified Shop',
    intelligentEta: 'Quick Route',
    prescriptionTitle: 'Send Prescription',
    ocrScanning: 'Easy Scan',
    pharmacistVerification: 'Check by Pharmacist',
    oneClickRefills: 'Quick Refills',
    uploadNow: 'Upload Now',
    dropImage: 'Click to upload photo',
    acceptedFiles: 'Accepted: JPG, PNG, PDF. Your medical data is safe with us.',
    voicesOfKaraikal: 'What our customers say',
    satisfiedNodes: 'Serving 10,000+ happy people in Karaikal.',
    districtTrusted: 'TRUSTED NETWORK',
    topRatedNode: 'TOP RATED SHOP',
    deliveryActive: 'DELIVERY IN PROGRESS',
    nodeHandshakeActive: 'CONNECTED',
    emergencyProtocolSync: 'Emergency Priority',
    searchPlaceholder: 'Search for medicine or pharmacy...',
    bookConsultation: 'Book Now',

    // About Page
    bornInKaraikal: 'Made in Karaikal',
    medireach: 'MediPharm',
    enclaveFounding: 'YEARS OF SERVICE',
    theHistory: 'OUR STORY',
    theStoryOf: 'THE STORY OF',
    marketRoad: 'MARKET ROAD',
    storyQuote: 'Helping patients find medicines easily in Karaikal.',
    storyParagraph1: 'MediPharm started in 2023. Our goal is to connect all local pharmacies into one easy website.',
    storyParagraph2: 'From our first shop on Market Road to serving all of Karaikal, we focus on trust and speed.',
    globalCustomers: 'LOCAL HOMES',
    enclaveOrders: 'SUCCESSFUL ORDERS',
    ourMission: 'OUR MISSION',
    missionText: 'To give everyone in Karaikal fast and safe access to medicines and doctors.',
    
    // Doctor Profile & Booking
    doctorProfile: 'Doctor Profile',
    consultationFee: 'Consultation Fee',
    bookAppointment: 'Book Appointment',
    verifiedMcReg: 'Verified MC Reg',
    consultingAt: 'Consulting at',
    yearsOfPractice: 'Years of Practice',
    experience: 'Experience',
    reviews: 'Reviews',
    schedule: 'Schedule',
    professionalBio: 'Professional Bio',
    education: 'Education',
    expertise: 'Expertise',
    consultationCalendar: 'Consultation Calendar',
    availableShifts: 'Available Shifts',
    architectureConsultation: 'Medical Consultation',
    selectCategory: 'Select Category',
    quickSymptoms: 'List Symptoms',
    symptomPlaceholder: 'Describe your symptoms...',
    selectedSlot: 'Selected Slot',
    confirmAndPay: 'Confirm & Pay',
    
    // Medicine Comparison
    compareProtocols: 'Compare Medicines',
    protocolUplink: 'Comparison tool',
    clinicalTrajectories: 'Compare medical details for up to 3 options in real-time.',
    addMedicine: 'Add Medicine',
    clearCompare: 'Clear All',
    medicineDetails: 'Medicine Details',
    indications: 'Indications',
    sideEffects: 'Side Effects',
    priceComparison: 'Price Comparison',


    ourVision: 'OUR VISION',
    visionText: 'To be the best healthcare app in town, delivering help to every home in 30 minutes.',
    districtPersonnel: 'OUR TEAM',
    meetThe: 'MEET THE',
    enclaveArchitects: 'THE TEAM',
    teamSubtitle: 'The people working hard to keep you healthy.',
    whatWeStandFor: 'VALUES',
    localFirstTitle: 'LOCAL FIRST',
    localFirstDesc: 'Built specifically for Karaikal roads and streets.',
    trustedVerificationTitle: 'TRUSTED SHOPS',
    trustedVerificationDesc: 'Every pharmacy is checked by local authorities.',
    zeroLagTitle: 'FAST SERVICE',
    zeroLagDesc: 'Quick delivery for emergency medicines.',
    universalAccessTitle: 'FOR EVERYONE',
    universalAccessDesc: 'Easy to use for everyone in Karaikal.',
    absoluteIntegrityTitle: 'SAFE DATA',
    absoluteIntegrityDesc: 'Your medical records are private and protected.',
    sustainableEnclaveTitle: 'ECO-FRIENDLY',
    sustainableEnclaveDesc: 'Optimized routes to save fuel and the environment.',
    theJourney: 'OUR PROGRESS',
    enclaveChronoview: 'TIMELINE',
    realtimeHistoricalSync: 'OUR HISTORY',
    milestone2023: 'First shop started on Market Road',
    milestone2024: 'Connected 8 major pharmacies',
    milestone2025: 'Started Doctor Video Calls',
    milestone2026: 'Covering the whole district',

    // Footer
    systemPulseActive: 'SYSTEM IS ONLINE',
    systemPulseOffline: 'SHOP IS OFFLINE',
    districtLargestNetwork: 'The largest network for medicines and doctors in Karaikal.',
    serviceClusters: 'SERVICES',
    registryNodes: 'RESOURCES',
    supportEnclave: 'SUPPORT',
    districtHub: 'LOCAL HUB',
    voiceSync: 'CALL US',
    emailSync: 'EMAIL US',
    stayHealthy: 'STAY HEALTHY',
    newsletterDesc: 'Get health tips and news delivered to your email.',
    emailAddressPlaceholder: 'Enter your email...',
    fastestSyncGuarantee: 'FAST DELIVERY GUARANTEE',
    securePayments: 'SECURE PAYMENT',
    madeForKaraikal: 'MADE FOR KARAIKAL',
    districtWideSync: 'CITY-WIDE SERVICE',
    meshId: 'SHOP ID',
    districtAuthorityAuthorized: 'AUTHORIZED PLATFORM',
    vaccines: 'Vaccines',

    // Localities
    loc_town: 'Karaikal Town',
    loc_newcolony: 'New Colony',
    loc_collectorate: 'Collectorate Street',
    loc_market: 'Market Road',
    loc_busstand: 'Bus Stand Area',
    loc_tvkoil: 'T.V.Koil Street',
    loc_poompuhar: 'Poompuhar Street',
    loc_nagore: 'Nagore Road',
    loc_keezha: 'Keezhakasakudimedu',

    // Generic
    welcomeBack: 'Welcome Back.',
    phoneOtp: 'Phone Code (OTP)',
    districtMobile: 'Phone Number',
    requestCode: 'Get Code',
    verifySync: 'Verify and Sign In',
    terminalAuth: 'Device Approval',
    enterCode: 'Enter the 4-digit code',
    verifying: 'Checking...',
    syncComplete: 'All Good!',
    continue: 'Continue',
    callNow: 'Call Now',
    
    // Auth
    registerTitle: 'Create Account',
    
    // Auth - Login Page
    loginHeroTitle: 'Your Health is Our Priority in Karaikal.',
    loginHeroSubtitle: 'The most reliable medicine delivery network in the district.',
    servingSince: 'Serving Karaikal since 2023',
    selectRoleDesc: 'Select your role to continue.',
    emailEncl: 'Email Address',
    secretProt: 'Password',
    rememberNode: 'Remember Me',
    forgotProt: 'Forgot Password?',
    authStream: 'Safe & Secure Login',
    enclMail: 'Email',
    newNode: 'New user?',
    initReg: 'Create Account',
    demoHub: 'Try Demo Account',

    // Auth - Register Page
    step1: 'Account Type',
    step2: 'Details',
    step3: 'Location',
    step4: 'Verification',
    step5: 'Profile',
    joiningEnclave: 'Join Karaikal\'s largest pharmaceutical network.',
    chooseNode: 'Who are you?',
    identityFoundation: 'Select your role to get started.',
    personalProtTitle: 'Tell us about yourself.',
    establishCreds: 'Enter your name and contact details.',
    fullNameId: 'Full Name',
    emailNode: 'Email',
    secretAccess: 'Password',
    proceedLoc: 'Next: Location',
    locEnclaveTitle: 'Where are you located?',
    karaikalSync: 'Provide your address for deliveries.',
    physAddr: 'Street Address',
    autoGps: 'Detect Location',
    initVerify: 'Send Code',
    codeSentStream: 'We sent a 6-digit code to your phone.',
    waitForSignal: 'Resend code in...',
    resendSignal: 'Resend Code',
    backLoc: 'Back to Address',
    profileIdTitle: 'Complete your profile.',
    uploadVisual: 'Add a photo so we can recognize you.',
    idSync: 'Display Picture',
    verifiedNodeProtocol: 'Highly recommended for medical professionals.',
    idNodePlaceholder: 'Profile Picture',
    pendingLog: 'No image selected',
    awaitingHandshake: 'Ready to upload',
    initHandshake: 'Create My Account',
    alreadyVerified: 'Already have an account?',
    termLogin: 'Login',

    // Search Results
    whatLookingFor: 'What are you looking for?',
    searchScanDesc: 'Search for medicines, pharmacies, and doctors in Karaikal.',
    noMatches: 'No results found for',
    resetSearch: 'Clear Search',
    viewMatches: 'View results',
    medicinesResults: 'Medicines',
    pharmaciesNodes: 'Pharmacies',
    doctorsAuthorities: 'Doctors',
    blogData: 'Blog Insights / data',
    bookConsultant: 'Book Consultant',

    // Medicine Detail
    skuNotFound: 'Pharmacy Not Found',
    skuNotFoundDesc: 'The requested clinical node {id} is not responding to district sync.',
    returnRegistry: 'Return to Registry',
    rxProtocol: 'Rx Protocol Required',
    molecularNode: 'Molecular Node',
    audits: 'AUDITS',
    soldInKKL: 'SOLD IN KARAIKAL',
    terminalPrice: 'Price',
    offPayload: 'Discount',
    unitsInStock: 'Units available',
    nodeOffline: 'Out of Stock',
    distributorNode: 'Distribution Node',
    verifiedNode: 'VERIFIED NODE',
    globalReach: 'Global Reach',
    protocolType: 'Protocol Type',
    initPayload: 'Add to Cart',
    instantUplink: 'Instant Uplink (Buy Now)',
    logisticsProtocol: 'Delivery Details',
    deliverToday: 'Deliver today by',
    regionalLatency: 'Regional Latency Node',
    similarNodes: 'Similar Clinical Nodes',
    initUniversalSync: 'Initialize Universal Sync',
    residentAudits: 'Verified Resident Audits',
    auditNode: 'Verified Audit Node',
    
    // Specifications
    specDescription: 'Description',
    specDosage: 'Dosage & Usage',
    specSideEffects: 'Side Effects',
    specStorage: 'Storage',
    specManufacturer: 'Manufacturer',

    // Home Sections C & Hospitals
    telemetryActive: 'Telemetry Active',
    standardProtocol: 'Standard Protocol',
    fee: 'Credit Fee',
    rating: 'Audit Rating',
    speedDelivery: 'Instant Sync',
    verifiedOnly: 'Verified Authority',
    liveMap: 'View Map',
    prioritySupport: '24/7 Enclave Support',
    refillAlerts: 'Refill Telemetry',
    refillAlertsDesc: 'Automatic Node Uplink',
    liveSupport: 'Support Uplink',
    clinicalInfrastructure: 'Medical Centers & Hospitals',
    gridMap: 'View Map',
    searchHospital: 'Search hospital name or area...',
    clinicalBeds: 'Available Beds',
    auditLevel: 'Accreditation',
    activeDepts: 'Specialties & Departments',
    emergencyLink: 'Emergency Contact',
    initSyncNode: 'View Details',
    universalEmergency: 'Emergency Services',
    emergencyNodePort: 'Emergency Support',
    instantDispatch: 'Call Ambulance',

    // Navbar & Layout
    systemOnline: 'System Online',
    systemOffline: 'System Offline',
    systemSyncActive: 'System Sync Active',
    markAll: 'Mark all',
    all: 'All',
    orders: 'Orders',
    noNotifications: 'No notifications',
    justNow: 'Just now',
    viewAll: 'View all',
    dashboard: 'Dashboard',
    myProfile: 'My Profile',
    wallet: 'Wallet',
    settings: 'Settings',
    accountSettings: 'Account Settings',
    joinMediReach: 'Join MediPharm',
    roleCeo: 'Founder & CEO',
    roleOps: 'Head of Operations',
    roleTech: 'Tech Architecture Lead',
    roleSuccess: 'Customer Success',
    lowStockAlert: 'Low Stock Alert: {name} Nodes depleted',
    lowStockNotify: '{name} is running low in inventory.',
    newOrderManifest: 'New Order Manifest Received',
    newProtocolManifest: 'New Protocol Manifest',
    incomingOrderMsg: 'Incoming order #{id} from patient node.',
    rxReviewActive: 'Prescription Uploaded: Review Protocol Active',
    clinicalManifestUploaded: 'Clinical Manifest Uploaded',
    rxReviewMsg: 'Prescription ready for review: Order #{id}',
    orderPlacingSuccess: 'Order #{id} placed successfully!',
    orderConfirmedBy: '{name} confirmed your order! Medicines are being prepared.',
    orderPreparingAt: '{name} is preparing your medicines. ETA: 25 min.',
    orderOutForDelivery: 'Your order is on the way! Agent: {name}. OTP: {otp}',
    orderDeliveredSuccess: 'Order delivered successfully! You earned {points} loyalty points! ★',
    orderCancelledBy: 'Order cancelled by pharmacy. Reason: {reason}. Full refund initiated.',
    rxVerifiedSuccess: 'Prescription verified! Your order is being prepared.',
    rxVerifiedReject: 'Prescription issue: {reason}. Please upload a clearer photo.',
    arrivalProximity: 'Arrival Proximity Alert: Agent 500m away! OTP: {otp}',
    newMissionAssigned: 'New Mission Assigned!',
    pickupReady: 'Pickup Ready: Order #{id}',
    sessionRevoked: 'Session Revoked: Account node offline.',
    identitySynced: 'Identity Synchronized: Enclave Verified.',

    // Registration & Toasts
    manageConsultations: 'Manage consultations',
    operateEnclave: 'Operate medical enclave',
    logisticsFulfillment: 'Logistics fulfillment',
    gpsSyncSuccess: 'GPS Protocol Synchronized',
    locationError: 'Location service not initialized',
    authSignalBroadcasted: 'Auth Signal Broadcasted',
    systemOverrideOtp: 'System Override: Test OTP is [ 123456 ]',
    registrationError: 'Registration Protocol Error',
    nodeVerified: 'Identity Node Verified',
    verificationFailed: 'Verification Sync Failed',
    visualHandshakeSync: 'Visual Handshake Synchronized',
    registrationFinalized: 'Registration Protocol Finalized',
    finalizationFailed: 'Finalization Sync Failed',
    syncedStatus: 'Synced: {size}MB',
    lowStockWarning: 'Low Stock Warning',
    orderPlaced: 'Order Placed!',
    orderPlacedMsg: 'Order #{id} synchronized at {pharmacyName}. Est. delivery: {eta}',
    orderPlacedToast: 'Order #{id} placed at {pharmacyName}!',
    statusSyncUpdate: 'Order protocol updated: {status}',
    protocolUpdate: 'Protocol Update',
    rxApprovedMsg: 'Prescription verified! Your order is being prepared.',
    rxRejectedMsg: 'Prescription issue: {reason}. Please upload a clearer photo.',
    rxApprovedTitle: 'RX Approved ✓',
    rxRejectedTitle: 'RX Rejected ✖',
    proximityAlert: 'Arrival Proximity Alert',
    deliveryAssignmentMsg: 'From: {pharmacyName} | To: {address} | Total: ₹{total}',

    // Login & Stats
    accessAuthorized: 'Access Protocol Authorized',
    authError: 'Authentication Error',
    invalidProtocolLength: 'Invalid Protocol Length',
    signalSyncFailed: 'Signal Sync Failed',
    identityRequired: 'Security Node Identity Required',
    ratingValue: '4.9/5 Rating',
    customerCount: '10K+ Customers',
    pharmacyCount: '8 Pharmacies',
    authAccessOnly: 'Authorized access only.',
    accessCodeOtp: 'Access Code (OTP)',
    sixDigitCode: '6-digit code',
    changeMobile: 'Change Mobile Number',
    synced: 'Synced',

    // Sidebar
    sidebarDashboard: 'Dashboard',
    sidebarMedicines: 'Medicines',
    sidebarDoctors: 'Doctors',
    sidebarMyOrders: 'My Orders',
    sidebarPrescriptions: 'Prescriptions',
    sidebarClinicalDesk: 'Medical Hub',
    sidebarWallet: 'Wallet',
    sidebarOperations: 'Operations',
    sidebarInventory: 'Inventory',
    sidebarOrderStream: 'Orders',
    sidebarYields: 'Earnings',
    sidebarNavigation: 'Directions',
    sidebarLiveNode: 'Live Map',
    sidebarProtocolLog: 'Activity Log',
    sidebarCommand: 'Admin Control',
    sidebarNodes: 'Shops',
    sidebarEnclaves: 'Areas',
    sidebarStreams: 'Updates',
    sidebarMetrics: 'Statistics',
    commandTerminal: 'Command Terminal',
    nodeVerifiedSide: 'Node Verified',
    sidebarSupport: 'District Support',
    sidebarSupportDesc: 'Direct architectural bridge to district headquarters.',

    // Settings
    settingsTitle: 'Settings.',
    commandProtocolEnclave: 'Command Protocol Enclave',
    accountProtocol: 'Account Protocol',
    alertStreams: 'Alert Streams',
    enclavePrivacy: 'Enclave Privacy',
    regionSync: 'Region & Sync',
    architectureHelp: 'Need Architecture Help?',
    districtSupportDesc: 'Connect to District Support Enclave',
    identityCredentials: 'Identity Credentials',
    currentProtocolPass: 'Current Protocol Pass',
    newNodeSecret: 'New Node Secret',
    updateAccessProtocol: 'Update Access Protocol',
    verificationStreams: 'Verification Streams',
    mobileEnclave: 'Mobile Enclave',
    reVerifyNode: 'Re-verify Node',
    emailStream: 'Email Stream',
    syncProtocol: 'Sync Protocol',
    purgeEnclaveNode: 'Purge Enclave Node',
    purgeDesc: 'Deleting your node will permanently scrub all prescriptions, orders, and consult records from the district enclave.',
    initiatePurge: 'Initiate Node Deletion Protocol',
    alertSyncProtocol: 'Alert Sync Protocol',
    orderUpdateStreams: 'Order Update Streams',
    pushSmsEnclave: 'Push + SMS Enclave',
    deliveryTrackingNode: 'Delivery Tracking Node',
    liveGpsProtocol: 'Live GPS Protocol',
    verificationAlerts: 'Verification Alerts',
    criticalPharmaSync: 'Critical Pharmaceutical Sync',
    healthSynchronizers: 'Health Synchronizers',
    medicineIntakePings: 'Medicine Intake Pings',
    promoEnclaveNodes: 'Promo Enclave Nodes',
    karaikalDistrictDeals: 'Karaikal District Deals',
    architectureDigest: 'Architecture Digest',
    weeklyHealthcareStream: 'Weekly Healthcare Stream',
    enclaveVisibility: 'Enclave Visibility',
    profileNodeVisibility: 'Profile Node Visibility',
    publicMedicalAuth: 'Public to medical authorities in Karaikal',
    dataSharingProtocol: 'Data Sharing Protocol',
    syncMedicalHistoryDoc: 'Sync medical history with verified doctors',
    gpsTrackingStream: 'GPS Tracking Stream',
    continuousLocationSync: 'Continuous location sync for emergency response',
    localizedArchitecture: 'Localized Architecture',
    languageEnclave: 'Language Enclave',
    englishProtocol: 'English Protocol',
    tamilStream: 'Tamil Stream',
    timezoneAuth: 'Timezone Auth',
    geographicalNode: 'Geographical Node',

    // Prescriptions
    myPrescriptions: 'My Prescriptions',
    prescriptionVaultDesc: 'Digital medical architecture vault for Karaikal residents.',
    dragPrescription: 'Drag prescription here or click to upload',
    cameraCapture: 'Camera Capture',
    acceptedFormats: 'Accepted: JPG, PNG, PDF | Max 10MB',
    processingMedicalArch: 'Processing Medical Architecture...',
    syncedStatusLabel: 'SYNCED',
    cancelUpload: 'Cancel Upload',
    myHistory: 'My History',
    verifiedBy: 'Verified by',
    prescribedDate: 'Prescribed Date',
    expiresOn: 'Expires On',
    archiveStatus: 'Archive Status',
    dispensedUsed: 'Dispensed (used)',
    medicinesIncluded: 'Medicines Included',
    orderRx: 'Order',
    cancelRx: 'Cancel',
    clinicalVaultSyncError: 'Failed to sync clinical vault',
    rxSyncSuccess: 'Prescription synchronized to mesh!',
    rxSyncError: 'Sync failed: Check network terminal',
    rxRemoved: 'Clinical node removed',
    rxDeleteError: 'Deletion protocol failed',

    // Pharmacist Dashboard
    incomingPayloads: 'Incoming Payloads',
    preparatorySync: 'Preparatory Sync',
    logisticsDeparture: 'Logistics Departure',
    districtRevenue: 'District Revenue',
    pharmacy: 'Pharmacy',
    enclaveNode: 'Enclave Node',
    liveClinicalTerminal: 'Live Clinical Terminal active',
    pharmacyEnclaveNode: 'Pharmacy Enclave Node',
    administratorNode: 'Administrator Node: Active',
    payloadManifest: 'Payload Manifest Terminal',
    realTime: 'Real-Time',
    districtHistory: 'District History',
    terminalIdle: 'Clinical Terminal Idle',
    uplinked: 'Uplinked',
    anonymousNode: 'Anonymous Node',
    karaikalEnclave: 'Karaikal Enclave',
    clinicalPayloadComponents: 'Clinical Payload Components',
    medicineNode: 'Medicine Node',
    verifyAuthorization: 'Verify Clinical Authorization',
    acceptNode: 'Accept Node Protocol',
    rejectSync: 'Reject Sync',
    logNode: 'Log Node',
    preparatoryRedline: 'Preparatory Redline',
    assemblingPayload: 'Assembling Payload...',
    dispatchPulse: 'Initiate Dispatch Pulse',
    terminalLock: 'Terminal Protocol Lock',
    emergencySecureMode: 'Emergency Secure Mode: Active',
    enterEnigma: 'Enter Enigma Code',
    realTimeChannels: 'Real-Time Channels',
    patientHandover: 'Patient Handover',
    districtAdmin: 'District Admin',
    payloadId: 'Payload',
    apolloHub: 'Apollo Pharmacy Hub',
    nodeSynchronized: 'Node Synchronized',
    protocolSyncFailed: 'Protocol Sync Failed',
    inventoryArchitecture: 'Inventory Architecture',
    liveEnclaveInventorySync: 'Live Enclave Inventory Sync',
    stockVelocity: 'Stock Velocity',
    enclaveRisk: 'Enclave Risk',
    criticalLowNodesDistrict: 'Critical Low Nodes Detected In District',
    replenishmentEfficiency: 'Replenishment Protocol Efficiency Increase',
    searchInventoryPlaceholder: 'Search by full medicine name or generic composition...',
    categoryArchitecture: 'Category Architecture',
    pulseDemand: 'Pulse Demand',
    registryMetrics: 'Registry Metrics',
    batchArchitectureNode: 'Batch Architecture Node',
    editNode: 'Edit Node',
    medicineRemovedInventory: 'Medicine removed from inventory',
    replenishmentProtocol: 'Replenishment Protocol',
    stockMatrixUnits: 'Stock Matrix Units',
    authorizeRegistry: 'Authorize Registry',
    financialEnclave: 'Financial Enclave',
    monthlyRevenueProtocol: 'Monthly Revenue Protocol',
    enclaveGrowth: 'Enclave Growth',
    orderFlowArchitecture: 'Order Flow Architecture',
    realTimeStreamProtocol: 'Real-time Stream Protocol',
    resourceNodeProtocol: 'Resource Node Protocol',
    medicineNamePlaceholder: 'Scientific Medicine Name (e.g. Paracetamol 500mg)',
    genericCodePlaceholder: 'Active Generic Chemistry Code',
    nodeValuation: 'Node Valuation',
    totalUnits: 'Total Units',
    unitFormat: 'Format (Packs / VL)',
    newMedicineSyncSuccess: 'New medicine architecture synchronized!',
    therapeuticIdentification: 'Therapeutic Identification',
    manufacturingBrand: 'Manufacturing Brand',
    
    // Blog & Articles
    articleNotFound: 'Article Architecture Not Found',
    backToBlog: 'Back to Blog',
    saveArticle: 'Save Article',
    shareArticle: 'Share Article',
    updateDate: 'Updated',
    recommended: 'Recommended',
    instantConsult: 'Instant Consult',
    copyLinkSuccess: 'Link copied to clipboard architecture!',
    needSupport: 'Need Medical Support?',
    bookConsultantNow: 'Book Consultant Now',
    navigation: 'Navigation',
    overview: 'Overview',
    primaryProtocol: 'Primary Protocol',
    doctorAdvice: 'Doctor Advice',
    conclusion: 'Conclusion',
    saveForLater: 'Save this for later?',
    saveArticleDesc: 'Bookmark this medical insight to your personal architecture profile.',
    viewFullArchitecture: 'View Full Architecture',
    consultArrow: 'Book Consultation →',

    // Shared UI
    enclaveSuffix: 'Enclave.',
    architectureSuffix: 'Architecture.',
    syncingEnclave: 'Syncing Enclave...',
    verifiedAuthority: 'Verified Authority',
    tabMedicines: 'Medicines',
    tabAbout: 'About',
    tabReviews: 'Reviews',
    tabOffers: 'Offers',

    // Hospitals
    districtArchitectureHeader: 'Healthcare in Karaikal',

    // Offers
    todaysBestOffers: "Today's Best Offers in Karaikal.",
    offersHeroDesc: "Exclusive medical offers from 12+ Karaikal district pharmacies.",
    flashSaleArch: "Flash Sale",
    discountVitamins: "20% OFF ALL VITAMIN SUPPLEMENTS",
    timeRemaining: "Time Remaining",
    shopAllVitamins: "Shop All Vitamins",
    copyCodeLabel: "Copy Code",
    viewProduct: "View Product",
    globalArchCodes: "Promo Codes",
    activePharmacyVouchers: "Active pharmacy vouchers for all Karaikal district residents.",
    codeCopied: "Code copied to clipboard! Ready to use.",

    // Emergency & Command Bar
    emergency: 'Emergency',
    emergencyHub: 'Emergency Hub',
    priorityProtocolActive: 'Priority Protocol Active',
    call108Emergency: 'Call 108 Emergency',
    instantAmbulanceSync: 'Instant Ambulance Sync',
    bloodRequest: 'Blood Request',
    districtBloodHub: 'District Blood Hub',
    oxygenPulse: 'Oxygen Pulse',
    liveSupplyLink: 'Live Supply Link',
    sosSupport: 'SOS Support',
    whatsappEnclave: 'WhatsApp Enclave',
    systemAuthorizedRapidResponse: 'System Authorized Rapid Response',
    searchNode: 'Search Node...',
    districtProtocolSync: 'District Protocol Sync',
    systemOnlineSynchronized: 'System Online Synchronized',
    activeDeliveries: '{count} Active Deliveries',
    nodeTerminalsOnline: '{count} Node Terminals Online',
    pressEscToExit: 'Press ESC to exit',
    searchMedicineNode: 'Search Medicine Node',
    scanDistrictInventoryClusters: 'Scan district inventory clusters',
    locateTerminalNodes: 'Locate Terminal Nodes',
    findVerifiedRegionalPharmacies: 'Find verified regional pharmacies',
    logisticsTelemetry: 'Logistics Telemetry',
    trackActiveDeliveryStreams: 'Track active delivery streams',
    teleconsultPulse: 'Teleconsult Pulse',
    syncWithCertifiedClinicians: 'Sync with certified clinicians',
    medicalVault: 'Medical Vault',
    accessEncryptedPrescriptions: 'Access encrypted prescriptions',
    systemHealth: 'System Health',
    districtArchitectureStatus: 'District architecture status',
    searchMedicines: 'Search Medicines',
    viewCart: 'View Cart'
  },

  ta: {
    // Navbar & Layout
    heroTitle: 'மாவட்ட மருத்துவ ஒத்திசைவு',
    heroSubtitle: 'காரைக்கால் கட்டளை.',
    heroDesc: 'உரிமம் பெற்ற மாவட்ட முனைகளுடன் உங்கள் மருத்துவத் தேவைகளை ஒத்திசைக்கவும். காரைக்கால் முழுவதும் நேரடித் தகவல்தொடர்பு.',
    orderNow: 'ஆர்டர் செய்',
    findNear: 'முனைகளைக் கண்டறியவும்',
    locate: 'கண்டறியவும்',
    karaikal: 'காரைக்கால் மண்டலம்',
    deliverTo: 'விநியோகிக்க வேண்டிய இடம்',
    activeNodes: '12 முனைகள் செயல்படுகின்றன',
    nodesOnline: 'அங்கீகரிக்கப்பட்டது & நேரலையில்',
    home: 'முதன்மை கட்டுப்பாடு',
    medicines: 'மருந்துகள்',
    pharmacies: 'மருந்தகங்கள்',
    doctors: 'மருத்துவர்',
    teleconsultation: 'மருத்துவர்',
    prescriptions: 'மருந்துச்சீட்டு',
    myOrders: 'ஆர்டர்கள்',
    about: 'எங்களைப் பற்றி',
    aboutUs: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு கொள்ள',
    offers: 'சலுகைகள்',
    blog: 'சுகாதாரத் தகவல்கள்',
    notifications: 'அமைப்பு எச்சரிக்கைகள்',
    myWallet: 'கடன் மேட்ரிக்ஸ்',
    helpSupport: 'தொழில்நுட்ப ஆதரவு',
    logout: 'வெளியேறு',
    logoutSystem: 'அங்கீகாரத்தை நீக்கி வெளியேறு',
    visitor: 'அங்கீகரிக்கப்பட்ட விருந்தினர்',
    login: 'உள்நுழை',
    register: 'பதிவு செய்',
    cart: 'கூடை',
    search: 'தேடல்',
    alerts: 'எச்சரிக்கைகள்',
    profile: 'சுயவிவர முனை',

    // Roles
    customer: 'வாடிக்கையாளர்',
    pharmacist: 'மருந்தாளர்',
    delivery: 'விநியோகப் பங்காளர்',
    admin: 'நிர்வாகி',
    enclave: 'பெட்டகம்',

    // Statuses
    pending: 'நிலுவையில் உள்ளது',
    verified: 'சரிபார்க்கப்பட்டது',
    shipped: 'அனுப்பப்பட்டது',
    delivered: 'விநியோகிக்கப்பட்டது',
    cancelled: 'ரத்து செய்யப்பட்டது',
    placed: 'ஆர்டர் செய்யப்பட்டது',
    confirmed: 'உறுதிப்படுத்தப்பட்டது',

    // Sidebar & Common
    commandTerminal: 'கட்டளை முனையம்',
    nodeVerifiedSide: 'முனை சரிபார்க்கப்பட்டது',
    sidebarSupport: 'மாவட்ட ஆதரவு',
    sidebarSupportDesc: 'மாவட்ட தலைமையகத்திற்கு நேரடி கட்டடக்கலை பாலம்.',

    // Stats & Categories
    statsPharmacies: 'மாவட்ட மருந்தகங்கள்',
    statsMedicines: 'மருந்து இருப்புப் பட்டியல்',
    statsDelivery: 'சராசரி விநியோக ஒத்திசைவு',
    statsCustomers: 'திருப்திகரமான மாவட்ட முனைகள்',
    shopCategory: 'பரிமாற்ற வகை',
    shopCategoryTitleMain: 'பரிமாற்ற',
    shopCategoryTitleSub: 'வகை',
    exploreCatalog: 'முழு இருப்புப் பட்டியலைப் பார்க்கவும்',
    browseCuratedClusters: 'காரைக்கால் மக்களுக்காக வடிவமைக்கப்பட்ட சுகாதாரத் தொகுப்புகள்.',
    accessNodes: 'முனைகளை அணுகவும்',
    
    // Popular Meds & Pharmacies
    popularMeds: 'பிரபலமான மருத்துவத் தகவல்கள்.',
    liveSync: 'நேரடி துடிப்பு ஒத்திசைவு',
    districtNode: 'மாவட்ட ஒத்திசைவு செயலில் உள்ளது',
    offlineNode: 'மாவட்ட முனை ஆஃப்லைனில் உள்ளது',
    verifiedHealthArchitecture: 'மாவட்டத்தின் ஒவ்வொரு வீட்டிற்கும் சரிபார்க்கப்பட்ட சுகாதார அமைப்பு.',
    initializingTelemetry: 'அமைப்புத் தகவலைத் தொடங்குகிறது...',
    districtNetwork: 'மாவட்ட நெட்வொர்க் இடைமுகம்',
    pharmaciesNear: 'பிராந்திய மருந்தக முனைகள்',
    verifiedLicensedPharmacies: 'காரைக்கால் முழுவதும் உரிமம் பெற்ற மருந்தகங்கள்.',
    openNow: 'ஒத்திசைவு செயலில் உள்ளது',
    freeDel: 'கட்டணமில்லா விநியோகம்',
    nodeRef: 'முனையக் குறிப்பு எண்',
    nodeActive: 'செயலில் உள்ளது',
    
    // Home Sections C
    vaccinesAvailable: 'காரைக்காலில் அங்கீகரிக்கப்பட்ட தடுப்பூசிகள்',
    dose: 'மருந்தளவு நெறிமுறை',
    priceCard: 'கட்டண அட்டை',
    storeLocation: 'முனை ஆதாரம்',
    available: 'ஒத்திசைவு கிடைக்கிறது',
    outOfStock: 'இருப்பு இல்லை',
    howItWorks: 'விநியோக கட்டமைப்பு',
    seamlessLogistics: 'தடையற்ற மாவட்ட விநியோகம்',
    districtArchitecture: 'காரைக்கால் மக்களுக்கு மெடிபார்ம் கட்டமைப்பு எவ்வாறு சேவை செய்கிறது.',
    searchMedicineTitle: 'மருந்து முனையைத் தேடுங்கள்',
    searchMedicineDesc: 'மாவட்ட இருப்பு முழுவதும் தானியங்கி கண்டறிதல்.',
    choosePharmacyTitle: 'முனையத்தை அங்கீகரிக்கவும்',
    choosePharmacyDesc: 'சரிபார்க்கப்பட்ட 8 மாவட்ட முனையங்களுடன் கைகுலுக்கல்.',
    payYourWayTitle: 'கடன் கைகுலுக்கல்',
    payYourWayDesc: 'மறைக்குறியிடப்பட்ட ஒத்திசைவு நெறிமுறைகள்.',
    liveGpsTitle: 'விநல்ல விநியோகத் தகவல்',
    liveGpsDesc: 'அதிநவீன வரைபடத்தின் மூலம் விநியோகத் தகவல்.',
    consultOnline: 'தொலைநிலைத் தொடர்பு ஆலோசனை',
    speakWithDoctors: '10 நிமிடங்களில் காரைக்கால் மருத்துவர்களுடன் பேசுங்கள்.',
    viewAllDoctors: 'அனைத்து மருத்துவர்களையும் அணுகவும்',
    gpsTrackingTitle: 'அதிநவீன வரைபடக் கட்டமைப்பு.',
    gpsTrackingDesc: 'காரைக்காலுக்காக சிறப்பாக வடிவமைக்கப்பட்ட ஜிபிஎஸ் வரைபடம்.',
    riderTelemetry: 'டெலிவரி தகவல் செயலில் உள்ளது',
    pharmacyVerification: 'முனையம் சரிபார்க்கப்பட்டது',
    intelligentEta: 'செயற்கை நுண்ணறிவு பாதை',
    prescriptionTitle: 'மருந்துச்சீட்டு பதிவேற்றம்',
    ocrScanning: 'உடனடி ஸ்கேனிங்',
    pharmacistVerification: 'சரிபார்ப்பு முறை',
    oneClickRefills: 'மீண்டும் நிரப்புதல்',
    uploadNow: 'பதிவேற்றத்தைத் தொடங்கவும்',
    dropImage: 'படத் தரவைப் பதிவேற்றவும்',
    acceptedFiles: 'ஏற்றுக்கொள்ளப்பட்டவை: JPG, PNG, PDF | அதிகபட்சம் 10MB. பாதுகாக்கப்பட்ட பெட்டகம்.',
    voicesOfKaraikal: 'காரைக்கால் நெட்வொர்க்கின் குரல்கள்',
    satisfiedNodes: 'மாவட்டத்தின் 10,000+ திருப்திகரமான முனைகளுக்கு சேவை செய்கிறோம்.',
    districtTrusted: 'மாவட்டத்தின் நம்பகமான நெட்வொர்க்',
    topRatedNode: 'உயர்தர முனையம்',
    deliveryActive: 'டெலிவரி தகவல் செயலில் உள்ளது',
    nodeHandshakeActive: 'முனை கைகுலுக்கல் பாதுகாப்பானது',
    emergencyProtocolSync: 'அவசரக்கால நெறிமுறை ஒத்திசைக்கப்பட்டது',
    searchPlaceholder: 'மருந்து அல்லது முனையைத் தேடுங்கள்...',
    bookConsultation: 'ஒத்திசைவைத் தொடங்கு',

    // About Page
    bornInKaraikal: 'காரைக்காலில் உருவானது',
    medireach: 'மெடிபார்ம்',
    enclaveFounding: 'ஆண்டுகள் வரலாறு',
    theHistory: 'வரலாறு',
    theStoryOf: 'கதை',
    marketRoad: 'மார்க்கெட் ரோடு',
    storyQuote: 'காரைக்காலின் கடலோரப் பகுதியில் மருந்தகங்களுக்கும் நோயாளிகளுக்கும் இடையிலான இடைவெளியைக் குறைத்தல்.',
    storyParagraph1: 'மெடிபார்ம் 2023 இல் காரைக்கால் மாவட்டத்தின் சிதறிய மருத்துவ இருப்புகளை ஒரு ஒருங்கிணைந்த வலையமைப்பாக மாற்றும் நோக்கத்துடன் தொடங்கப்பட்டது.',
    storyParagraph2: 'மார்க்கெட் ரோட்டில் எங்களின் முதல் விநியோகத்திலிருந்து இன்று காரைக்கால் முழுவதும் நம்பகமான சேவையை வழங்கி வருகிறோம்.',
    globalCustomers: 'மாவட்ட வீடுகள்',
    enclaveOrders: 'வெற்றிகரமான விநியோகங்கள்',
    ourMission: 'எங்கள் நோக்கம்',
    missionText: 'காரைக்காலின் ஒவ்வொரு குடிமகனுக்கும் உடனடி, பாதுகாப்பான மற்றும் சரிபார்க்கப்பட்ட மருத்துவ வசதியை வழங்குவது.',
    
    // Doctor Profile & Booking
    doctorProfile: 'மருத்துவர் சுயவிவரம்',
    consultationFee: 'ஆலோசனை கட்டணம்',
    bookAppointment: 'சந்திப்பைப் பதிவு செய்யவும்',
    verifiedMcReg: 'சரிபார்க்கப்பட்ட MC பதிவு',
    consultingAt: 'இங்கே பணியாற்றுகிறார்',
    yearsOfPractice: 'ஆண்டு கால அனுபவம்',
    experience: 'அனுபவம்',
    reviews: 'மதிப்பாய்வுகள்',
    schedule: 'அட்டவணை',
    professionalBio: 'தொழில்முறை சுயவிவரம்',
    education: 'கல்வி',
    expertise: 'நிபுணத்துவம்',
    consultationCalendar: 'ஆலோசனை காலண்டர்',
    availableShifts: 'கிடைக்கும் நேரங்கள்',
    architectureConsultation: 'மருத்துவ ஆலோசனை',
    selectCategory: 'வகையைத் தேர்ந்தெடுக்கவும்',
    quickSymptoms: 'அறிகுறிகள்',
    symptomPlaceholder: 'உங்கள் அறிகுறிகளை விவரிக்கவும்...',
    selectedSlot: 'தேர்ந்தெடுக்கப்பட்ட நேரம்',
    confirmAndPay: 'உறுதிசெய்து பணம் செலுத்தவும்',
    
    // Medicine Comparison
    compareProtocols: 'மருந்து ஒப்பீடு',
    protocolUplink: 'ஒப்பீட்டு தளம்',
    clinicalTrajectories: '3 மருந்துகள் வரை அவற்றின் விவரங்களை ஒப்பிடுங்கள்.',
    addMedicine: 'மருந்தைச் சேர்க்கவும்',
    clearCompare: 'அனைத்தையும் நீக்கவும்',
    medicineDetails: 'மருந்து விவரங்கள்',
    indications: 'பயன்பாடு',
    sideEffects: 'பக்க விளைவுகள்',
    priceComparison: 'விலை ஒப்பீடு',


    ourVision: 'எங்கள் பார்வை',
    visionText: 'மாவட்ட சுகாதாரத்தின் டிஜிட்டல் இதயமாக மாறுவது.',
    districtPersonnel: 'மாவட்ட பணியாளர்கள்',
    meetThe: 'சந்திக்கவும்',
    enclaveArchitects: 'திட்ட வடிவமைப்பாளர்கள்',
    teamSubtitle: 'மெடிரீச் கட்டுப்பாட்டு மையத்தை நிர்வகிக்கும் பொறியாளர்கள் மற்றும் மருத்துவர்கள்.',
    whatWeStandFor: 'நாங்கள் எதற்காக நிற்கிறோம்',
    localFirstTitle: 'உள்ளூர் முதன்மை',
    localFirstDesc: 'காரைக்காலின் புவியியல் அமைப்புக்கு உகந்த வடிவமைப்பு.',
    trustedVerificationTitle: 'நம்பகமான சரிபார்ப்பு',
    trustedVerificationDesc: 'ஒவ்வொரு முனையும் மாவட்ட அதிகாரிகளால் சரிபார்க்கப்படுகிறது.',
    zeroLagTitle: 'தாமதமற்ற சேவை',
    zeroLagDesc: 'அவசரகால விநியோகத்திற்கான அதிவேகத் தகவல் தொடர்பு.',
    universalAccessTitle: 'அனைவருக்கும் அணுகல்',
    universalAccessDesc: 'சமூகத்தின் அனைத்து தரப்பினருக்கும் தடையற்ற ஒத்திசைவு.',
    absoluteIntegrityTitle: 'முழுமையான நேர்மை',
    absoluteIntegrityDesc: 'மருத்துவ பெட்டகத்திற்கான எண்ட்-டு-எண்ட் என்க்ரிப்ஷன்.',
    sustainableEnclaveTitle: 'நிலையான மண்டலம்',
    sustainableEnclaveDesc: 'சுற்றுச்சூழல் பாதிப்பைக் குறைக்க உகந்த பாதைகள்.',
    theJourney: 'பயணம்',
    enclaveChronoview: 'காலவரிசை',
    realtimeHistoricalSync: 'நிகழ்நேர வரலாற்று ஒத்திசைவு',
    milestone2023: 'மார்க்கெட் ரோட்டில் சேவை தொடக்கம்',
    milestone2024: '8 அங்கீகரிக்கப்பட்ட முனையங்கள் இணைப்பு',
    milestone2025: 'தொலைநிலை கலந்தாய்வு அறிமுகம்',
    milestone2026: 'மாவட்டம் முழுவதும் முழுமையான ஒத்திசைவு',

    // Footer
    systemPulseActive: 'அமைப்புத் துடிப்பு செயலில் உள்ளது',
    systemPulseOffline: 'முனை முடக்கப்பட்டது',
    districtLargestNetwork: 'காரைக்கால் மாவட்டத்தின் ஒருங்கிணைந்த மருத்துவ விநியோக வலையமைப்பு.',
    serviceClusters: 'சேவை தொகுப்புகள்',
    registryNodes: 'பதிவு முனைகள்',
    supportEnclave: 'ஆதரவு மையம்',
    districtHub: 'மாவட்ட மையம்',
    voiceSync: 'குரல் ஒத்திசைவு',
    emailSync: 'மின்னஞ்சல் ஒத்திசைவு',
    stayHealthy: 'ஆரோக்கியமாக இருங்கள்',
    newsletterDesc: 'நிகழ்நேர அறிவிப்புகளுக்கு மாவட்ட சுகாதார தகவல்களுக்கு குழுசேரவும்.',
    emailAddressPlaceholder: 'மின்னஞ்சலை உள்ளிடவும்...',
    fastestSyncGuarantee: 'வேகமான விநியோக உறுதி',
    securePayments: 'பாதுகாப்பான கட்டணம்',
    madeForKaraikal: 'காரைக்காலுக்காக உருவாக்கப்பட்டது',
    districtWideSync: 'மாவட்டம் தழுவிய ஒத்திசைவு',
    meshId: 'முனை அடையாளம்',
    districtAuthorityAuthorized: 'மாவட்ட அதிகாரத்தால் அங்கீகரிக்கப்பட்டது',
    vaccines: 'தடுப்பூசி பட்டியல்',

    // Localities
    loc_town: 'காரைக்கால் நகரம்',
    loc_newcolony: 'நியூ காலனி',
    loc_collectorate: 'கலெக்டரேட் சாலை',
    loc_market: 'மார்க்கெட் ரோடு',
    loc_busstand: 'பேருந்து நிலைய பகுதி',
    loc_tvkoil: 'டி.வி. கோவில் வீதி',
    loc_poompuhar: 'பூம்புகார் சாலை',
    loc_nagore: 'நாகூர் ரோடு',
    loc_keezha: 'கீழக்கசக்குடிமேடு',

    // Generic
    welcomeBack: 'மீண்டும் வருக, தளபதியே.',
    phoneOtp: 'கைகுலுக்கல் OTP',
    districtMobile: 'அங்கீகரிக்கப்பட்ட மொபைல் ஐடி',
    requestCode: 'குறியீட்டைக் கோருங்கள்',
    verifySync: 'சரிபார்த்து அங்கீகரிக்கவும்',
    terminalAuth: 'முனைய அங்கீகாரம்',
    enterCode: 'அங்கீகாரக் குறியீட்டை உள்ளிடவும்',
    verifying: 'பாதுகாப்பு நெறிமுறையைச் சரிபார்க்கிறது...',
    syncComplete: 'ஒத்திசைவு முடிந்தது',
    continue: 'தொடரவும்',
    callNow: 'அழைப்பைத் தொடங்கு',
    
    // Auth
    registerTitle: 'முனைப் பதிவைத் தொடங்கவும்',

    // Auth - Login Page
    loginHeroTitle: 'காரைக்காலில் உங்கள் ஆரோக்கியம் எங்கள் [நோக்கம்].',
    loginHeroSubtitle: 'மாவட்டத்தின் மிகவும் உள்ளூர்மயமாக்கப்பட்ட மருந்து விநியோக முனையத்தை அணுகவும்.',
    servingSince: '2023 முதல் காரைக்காலில் சேவை செய்கிறது',
    selectRoleDesc: 'முனையத்தை அணுக உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்.',
    emailEncl: 'மின்னஞ்சல் பெட்டகம்',
    secretProt: 'ரகசிய நெறிமுறை',
    rememberNode: 'முனையை நினைவில் கொள்க',
    forgotProt: 'ரகசியக் குறியீடு மறந்ததா?',
    authStream: 'டிஜிட்டல் அங்கீகாரத் தகவல்',
    enclMail: 'பெட்டக மின்னஞ்சல்',
    newNode: 'நெட்வொர்க்கில் புதிய முனையா?',
    initReg: 'பதிவைத் தொடங்கவும்',
    demoHub: 'மாதிரி அணுகல் மையம்',

    // Auth - Register Page
    step1: 'அடையாள முனை',
    step2: 'தனிப்பட்ட நெறிமுறை',
    step3: 'இருப்பிடப் பெட்டகம்',
    step4: 'அங்கீகாரச் சரிபார்ப்பு',
    step5: 'சுயவிவர அடையாளம்',
    joiningEnclave: 'மாவட்டத்தின் மிகப்பாதுகாப்பான மருந்து விநியோக கட்டமைப்பில் நுழைகிறீர்கள்.',
    chooseNode: 'உங்கள் முனையைத் தேர்வு செய்யவும்.',
    identityFoundation: 'அடையாளம் என்பது பெட்டக அணுகலின் அடிப்படை.',
    personalProtTitle: 'தனிப்பட்ட நெறிமுறை.',
    establishCreds: 'உங்கள் பாதுகாப்பான முனை நற்சான்றிதழ்களை உருவாக்கவும்.',
    fullNameId: 'முழு அடையாளப் பெயர்',
    emailNode: 'மின்னஞ்சல் முனை',
    secretAccess: 'ரகசிய அணுகல் குறியீடு',
    proceedLoc: 'இருப்பிடத்திற்குச் செல்லவும்',
    locEnclaveTitle: 'இருப்பிடப் பெட்டகம்.',
    karaikalSync: 'காரைக்கால் மாவட்ட முனை ஒத்திசைவு.',
    physAddr: 'இருப்பிட முகவரி',
    autoGps: 'தானியங்கி ஜிபிஎஸ்',
    initVerify: 'சரிபார்ப்பைத் தொடங்கவும்',
    codeSentStream: 'மொபைலுக்கு குறியீடு அனுப்பப்பட்டது.',
    waitForSignal: 'சமிக்ஞைக்காகக் காத்திருங்கள்...',
    resendSignal: 'சமிக்ஞையை மீண்டும் அனுப்பவும்',
    backLoc: 'இருப்பிடத்திற்குத் திரும்பு',
    profileIdTitle: 'சுயவிவர அடையாளம்.',
    uploadVisual: 'சரிபார்க்கப்பட்ட அணுகலுக்கு முனைப் படத்தைப் பதிவேற்றவும்.',
    idSync: 'அடையாள ஒத்திசைவு.',
    verifiedNodeProtocol: 'சரிபார்க்கப்பட்ட மாவட்ட முனை அங்கீகார நெறிமுறை.',
    idNodePlaceholder: 'அடையாள முனை',
    pendingLog: 'சரிபார்ப்பு நிலுவையில் உள்ளது.LOG',
    awaitingHandshake: 'கைகுலுக்கலுக்காகக் காத்திருக்கிறது...',
    initHandshake: 'முனையக் கைகுலுக்கலைத் தொடங்கவும்',
    alreadyVerified: 'ஏற்கனவே சரிபார்க்கப்பட்ட முனையா?',
    termLogin: 'முனைய உள்நுழைவு',

    // Search Results
    whatLookingFor: 'நீங்கள் எதைத் தேடுகிறீர்கள்?',
    searchScanDesc: 'காரைக்கால் பெட்டகத்தை ஸ்கேன் செய்ய மருத்துவ வினவலை உள்ளிடவும்.',
    noMatches: 'இதற்கான முடிவுகள் எதுவும் இல்லை',
    resetSearch: 'தேடலை மீட்டமைக்கவும்',
    viewMatches: 'முடிவுகளைக் காண்க',
    medicinesResults: 'மருந்துகள் / முடிவுகள்',
    pharmaciesNodes: 'மருந்தகங்கள் / முனைகள்',
    doctorsAuthorities: 'மருத்துவர்கள் / அதிகாரப் பூர்வமானவர்கள்',
    blogData: 'வலைப்பதிவு நுண்ணறிவு / தரவு',
    bookConsultant: 'ஆலோசனையைப் பதிவு செய்யவும்',

    // Medicine Detail
    skuNotFound: 'பொருள் கிடைக்கவில்லை',
    skuNotFoundDesc: 'கோரப்பட்ட மருத்துவ முனை மாவட்ட ஒத்திசைவுக்கு பதிலளிக்கவில்லை.',
    returnRegistry: 'பதிவேட்டிற்குத் திரும்பு',
    rxProtocol: 'மருத்துவரின் பரிந்துரை தேவை',
    molecularNode: 'மூலக்கூறு முனை',
    audits: 'மதிப்பாய்வுகள்',
    soldInKKL: 'காரைக்காலில் விற்கப்பட்டது',
    terminalPrice: 'முனைய விலை',
    offPayload: 'விலை குறைப்பு',
    unitsInStock: 'இருப்பு உள்ளது',
    nodeOffline: 'முனை ஆஃப்லைனில் உள்ளது',
    distributorNode: 'விநியோக முனை',
    verifiedNode: 'சரிபார்க்கப்பட்ட முனை',
    globalReach: 'உலகளாவிய அணுகல்',
    protocolType: 'நெறிமுறை வகை',
    initPayload: 'பொருளைச் சேர்க்கவும்',
    instantUplink: 'உடனடி கொள்முதல்',
    logisticsProtocol: 'தளவாட நெறிமுறை',
    deliverToday: 'இன்று விநியோகிக்கப்படும்: ',
    regionalLatency: 'மண்டல தாமத முனை',
    similarNodes: 'ஒத்த மருத்துவ முனைகள்',
    initUniversalSync: 'ஒத்திசைவைத் தொடங்கவும்',
    residentAudits: 'சரிபார்க்கப்பட்ட குடியிருப்பாளர் மதிப்பாய்வுகள்',
    auditNode: 'சரிபார்க்கப்பட்ட மதிப்பாய்வு முனை',

    // Specifications
    specDescription: 'விளக்கம்',
    specDosage: 'அளவு மற்றும் பயன்பாடு',
    specSideEffects: 'பக்க விளைவுகள்',
    specStorage: 'சேமிப்பு',
    specManufacturer: 'உற்பத்தியாளர்',

    // Home Sections C & Hospitals
    telemetryActive: 'தகவல் செயலில் உள்ளது',
    standardProtocol: 'நிலையான நெறிமுறை',
    fee: 'ஆலோசனை கட்டணம்',
    rating: 'மதிப்பாய்வு தரம்',
    speedDelivery: 'உடனடி ஒத்திசைவு',
    verifiedOnly: 'சரிபார்க்கப்பட்ட அதிகாரம்',
    liveMap: 'நேரடி வரைபடம்',
    prioritySupport: '24/7 மாவட்ட ஆதரவு',
    refillAlerts: 'மருந்து நிரப்புதல் தகவல்',
    refillAlertsDesc: 'தானியங்கி முனை இணைப்பு',
    liveSupport: 'நேரடி ஆதரவு',
    clinicalInfrastructure: 'சிகிச்சை உள்கட்டமைப்பு மையம்',
    gridMap: 'வரைபடத்தைப் பார்க்கவும்',
    searchHospital: 'மருத்துவமனை பெயர் அல்லது பகுதியைத் தேடுங்கள்...',
    clinicalBeds: 'சிகிச்சை படுக்கைகள்',
    auditLevel: 'ஆடிட் நிலை',
    activeDepts: 'செயலில் உள்ள துறைகள்',
    emergencyLink: 'அவசரக்கால இணைப்பு',
    initSyncNode: 'ஒத்திசைவு முனையைத் தொடங்கவும்',
    universalEmergency: 'உலகளாவிய அவசரகால இணைப்பு',
    emergencyNodePort: 'அவசரகால முனை போர்ட்',
    instantDispatch: 'உடனடி விநியோக நெறிமுறை',

    // Navbar & Layout
    systemOnline: 'அமைப்பு ஆன்லைனில் உள்ளது',
    systemOffline: 'அமைப்பு ஆஃப்லைனில் உள்ளது',
    systemSyncActive: 'அமைப்பு ஒத்திசைவு செயலிலுள்ளது',
    markAll: 'அனைத்தையும் படி',
    all: 'அனைத்தும்',
    orders: 'ஆர்டர்கள்',
    noNotifications: 'அறிவிப்புகள் இல்லை',
    justNow: 'இப்போது',
    viewAll: 'அனைத்தையும் பார்க்க',
    dashboard: 'கட்டுப்பாட்டு அறை',
    myProfile: 'எனது சுயவிவரம்',
    wallet: 'எனது பணப்பை',
    settings: 'அமைப்புகள்',
    accountSettings: 'கணக்கு அமைப்புகள்',
    joinMediReach: 'மெடிபார்மில் சேரவும்',
    roleCeo: 'நிறுவனர் மற்றும் சிஇஓ',
    roleOps: 'செயல்பாட்டுத் தலைவர்',
    roleTech: 'தொழில்நுட்பத் தலைவர்',
    roleSuccess: 'வாடிக்கையாளர் வெற்றி',

    // Registration & Toasts
    manageConsultations: 'ஆலோசனைகளை நிர்வகிக்கவும்',
    operateEnclave: 'மருத்துவ பெட்டகத்தை இயக்கவும்',
    logisticsFulfillment: 'விநியோகத்தை நிறைவேற்றவும்',
    gpsSyncSuccess: 'ஜிபிஎஸ் நெறிமுறை ஒத்திசைக்கப்பட்டது',
    locationError: 'இருப்பிட சேவை தொடங்கப்படவில்லை',
    authSignalBroadcasted: 'அங்கீகார சமிக்ஞை ஒளிபரப்பப்பட்டது',
    systemOverrideOtp: 'அமைப்பு மேலெழுதல்: சோதனை OTP [ 123456 ]',
    registrationError: 'பதிவு நெறிமுறை பிழை',
    nodeVerified: 'அடையாள முனை சரிபார்க்கப்பட்டது',
    verificationFailed: 'சரிபார்ப்பு ஒத்திசைவு தோல்வியடைந்தது',
    visualHandshakeSync: 'காட்சிக் கைகுலுக்கல் ஒத்திசைக்கப்பட்டது',
    registrationFinalized: 'பதிவு நெறிமுறை இறுதி செய்யப்பட்டது',
    finalizationFailed: 'இறுதியாக்க ஒத்திசைவு தோல்வியடைந்தது',

    // Login & Stats
    accessAuthorized: 'அணுகல் நெறிமுறை அங்கீகரிக்கப்பட்டது',
    authError: 'அங்கீகார பிழை',
    invalidProtocolLength: 'தவறான நெறிமுறை நீளம்',
    signalSyncFailed: 'சமிக்ஞை ஒத்திசைவு தோல்வியடைந்தது',
    identityRequired: 'பாதுகாப்பு முனை அடையாளம் தேவை',
    ratingValue: '4.9/5 மதிப்பாய்வு',
    customerCount: '10K+ வாடிக்கையாளர்கள்',
    pharmacyCount: '8 மருந்தகங்கள்',
    authAccessOnly: 'அங்கீகரிக்கப்பட்ட அணுகல் மட்டுமே.',
    accessCodeOtp: 'அணுகல் குறியீடு (OTP)',
    sixDigitCode: '6-இலக்க குறியீடு',
    changeMobile: 'மொபைல் எண்ணை மாற்றவும்',
    synced: 'ஒத்திசைக்கப்பட்டது',

    // Sidebar
    sidebarDashboard: 'கட்டுப்பாட்டு அறை',
    sidebarMedicines: 'மருந்துகள்',
    sidebarDoctors: 'மருத்துவர்கள்',
    sidebarMyOrders: 'எனது ஆர்டர்கள்',
    sidebarPrescriptions: 'மருந்துச்சீட்டுகள்',
    sidebarClinicalDesk: 'மருத்துவ மேஜை',
    sidebarWallet: 'பணப்பை',
    sidebarOperations: 'செயல்பாடுகள்',
    sidebarInventory: 'இருப்பு',
    sidebarOrderStream: 'ஆர்டர் ஓட்டம்',
    sidebarYields: 'விளைச்சல்',
    sidebarNavigation: 'வழிசெலுத்தல்',
    sidebarLiveNode: 'நேரடி முனை',
    sidebarProtocolLog: 'நெறிமுறை பதிவு',
    sidebarCommand: 'கட்டளை',
    sidebarNodes: 'முனைகள்',
    sidebarEnclaves: 'பெட்டகங்கள்',
    sidebarStreams: 'ஓட்டங்கள்',
    sidebarMetrics: 'அளவீடுகள்',

    // Settings
    settingsTitle: 'அமைப்புகள்.',
    commandProtocolEnclave: 'கட்டளை நெறிமுறை பெட்டகம்',
    accountProtocol: 'கணக்கு நெறிமுறை',
    alertStreams: 'எச்சரிக்கை ஓட்டங்கள்',
    enclavePrivacy: 'பெட்டக தனியுரிமை',
    regionSync: 'பிராந்தியம் மற்றும் ஒத்திசைவு',
    architectureHelp: 'கட்டடக்கலை உதவி வேண்டுமா?',
    districtSupportDesc: 'மாவட்ட ஆதரவு பெட்டகத்துடன் இணைக்கவும்',
    identityCredentials: 'அடையாளச் சான்றுகள்',
    currentProtocolPass: 'தற்போதைய நெறிமுறை கடவுச்சொல்',
    newNodeSecret: 'புதிய முனை இரகசியம்',
    updateAccessProtocol: 'அணுகல் நெறிமுறையைப் புதுப்பிக்கவும்',
    verificationStreams: 'சரிபார்ப்பு ஓட்டங்கள்',
    mobileEnclave: 'மொபைல் பெட்டகம்',
    reVerifyNode: 'முனையை மீண்டும் சரிபார்க்கவும்',
    emailStream: 'மின்னஞ்சல் ஓட்டம்',
    syncProtocol: 'ஒத்திசைவு நெறிமுறை',
    purgeEnclaveNode: 'முனை பெட்டகத்தை நீக்கு',
    purgeDesc: 'உங்கள் முனையை நீக்குவது மாவட்ட பெட்டகத்திலிருந்து அனைத்து மருந்துச்சீட்டுகள், ஆர்டர்கள் மற்றும் ஆலோசனை பதிவுகளையும் நிரந்தரமாக அகற்றும்.',
    initiatePurge: 'முனை நீக்குதல் நெறிமுறையைத் தொடங்கவும்',
    alertSyncProtocol: 'எச்சரிக்கை ஒத்திசைவு நெறிமுறை',
    orderUpdateStreams: 'ஆர்டர் புதுப்பிப்பு ஓட்டங்கள்',
    pushSmsEnclave: 'புஷ் + எஸ்எம்எஸ் பெட்டகம்',
    deliveryTrackingNode: 'விநியோக கண்காணிப்பு முனை',
    liveGpsProtocol: 'நேரடி ஜிபிஎஸ் நெறிமுறை',
    verificationAlerts: 'சரிபார்ப்பு எச்சரிக்கைகள்',
    criticalPharmaSync: 'முக்கியமான மருந்து ஒத்திசைவு',
    healthSynchronizers: 'ஆரோக்கிய ஒத்திசைவுகள்',
    medicineIntakePings: 'மருந்து உட்கொள்ளும் அறிவிப்புகள்',
    promoEnclaveNodes: 'விளம்பர முனை பெட்டகங்கள்',
    karaikalDistrictDeals: 'காரைக்கால் மாவட்ட சலுகைகள்',
    architectureDigest: 'கட்டடக்கலை சுருக்கம்',
    weeklyHealthcareStream: 'வாராந்திர சுகாதார ஓட்டம்',
    enclaveVisibility: 'பெட்டக தெரிவுநிலை',
    profileNodeVisibility: 'சுயவிவர முனை தெரிவுநிலை',
    publicMedicalAuth: 'காரைக்காலில் உள்ள மருத்துவ அதிகாரிகளுக்கு பொதுவானது',
    dataSharingProtocol: 'தரவு பகிர்வு நெறிமுறை',
    syncMedicalHistoryDoc: 'சரிபார்க்கப்பட்ட மருத்துவர்களுடன் மருத்துவ வரலாற்றை ஒத்திசைக்கவும்',
    gpsTrackingStream: 'ஜிபிஎஸ் கண்காணிப்பு ஓட்டம்',
    continuousLocationSync: 'அவசரகால பதிலுக்கான தொடர்ச்சியான இருப்பிட ஒத்திசைவு',
    localizedArchitecture: 'உள்ளூர்மயமாக்கப்பட்ட கட்டடக்கலை',
    languageEnclave: 'மொழி பெட்டகம்',
    englishProtocol: 'ஆங்கில நெறிமுறை',
    tamilStream: 'தமிழ் ஓட்டம்',
    timezoneAuth: 'நேர மண்டல அங்கீகாரம்',
    geographicalNode: 'புவியியல் முனை',

    // Prescriptions
    myPrescriptions: 'எனது மருந்துச்சீட்டுகள்',
    prescriptionVaultDesc: 'காரைக்கால் குடியிருப்பாளர்களுக்கான டிஜிட்டல் மருத்துவ பெட்டகம்.',
    dragPrescription: 'இங்கே இழுக்கவும் அல்லது பதிவேற்ற கிளிக் செய்யவும்',
    cameraCapture: 'கேமரா பிடிப்பு',
    acceptedFormats: 'ஏற்கத்தக்கவை: JPG, PNG, PDF | அதிகபட்சம் 10MB',
    processingMedicalArch: 'மருத்துவ கட்டமைப்பு செயலாக்கப்படுகிறது...',
    syncedStatusLabel: 'ஒத்திசைக்கப்பட்டது',
    cancelUpload: 'பதிவேற்றத்தை ரத்துசெய்',
    myHistory: 'எனது வரலாறு',
    verifiedBy: 'சரிபார்க்கப்பட்டது',
    prescribedDate: 'பரிந்துரைக்கப்பட்ட தேதி',
    expiresOn: 'காலாவதியாகும் தேதி',
    archiveStatus: 'காப்பக நிலை',
    dispensedUsed: 'விநியோகிக்கப்பட்டது (பயன்படுத்தப்பட்டது)',
    medicinesIncluded: 'சேர்க்கப்பட்டுள்ள மருந்துகள்',
    orderRx: 'ஆர்டர்',
    cancelRx: 'ரத்துசெய்',
    clinicalVaultSyncError: 'மருத்துவ பெட்டகத்தை ஒத்திசைக்க முடியவில்லை',
    rxSyncSuccess: 'மருந்துச்சீட்டு ஒத்திசைக்கப்பட்டது!',
    rxSyncError: 'ஒத்திசைவு தோல்வியடைந்தது: நெட்வொர்க் முனையத்தை சரிபார்க்கவும்',
    lowStockWarning: 'குறைந்த இருப்பு எச்சரிக்கை',
    orderPlaced: 'ஆர்டர் செய்யப்பட்டது!',
    orderPlacedMsg: 'ஆர்டர் #{id} {pharmacyName} இல் ஒத்திசைக்கப்பட்டது. விநியோக நேரம்: {eta}',
    orderPlacedToast: 'ஆர்டர் #{id} {pharmacyName} இல் செய்யப்பட்டது!',
    statusSyncUpdate: 'ஆர்டர் நெறிமுறை புதுப்பிக்கப்பட்டது: {status}',
    protocolUpdate: 'நெறிமுறை இணக்கம்',
    rxApprovedMsg: 'மருந்துச்சீட்டு சரிபார்க்கப்பட்டது! உங்கள் ஆர்டர் தயாராக உள்ளது.',
    rxRejectedMsg: 'மருந்துச்சீட்டுப் பிரச்சனை: {reason}. தெளிவான புகைப்படத்தைப் பதிவேற்றவும்.',
    rxApprovedTitle: 'RX அங்கீகரிக்கப்பட்டது ✓',
    rxRejectedTitle: 'RX நிராகரிக்கப்பட்டது ✖',
    proximityAlert: 'அருகாமை எச்சரிக்கை',
    deliveryAssignmentMsg: 'இருந்து: {pharmacyName} | வரை: {address} | மொத்தம்: ₹{total}',
    lowStockAlert: 'குறைந்த இருப்பு எச்சரிக்கை: {name} முனைகள் காலியாக உள்ளன',
    lowStockNotify: '{name} இருப்பு குறைவாக உள்ளது.',
    newOrderManifest: 'புதிய ஆர்டர் மேனிஃபெஸ்ட் பெறப்பட்டது',
    newProtocolManifest: 'புதிய நெறிமுறை மேனிஃபெஸ்ட்',
    incomingOrderMsg: 'நோயாளி மூலமாக ஆர்டர் #{id} வந்துள்ளது.',
    rxReviewActive: 'மருந்துச்சீட்டு பதிவேற்றப்பட்டது: மதிப்பாய்வு செயலில் உள்ளது',
    clinicalManifestUploaded: 'மருத்துவ மேனிஃபெஸ்ட் பதிவேற்றப்பட்டது',
    rxReviewMsg: 'மதிப்பாய்வு செய்ய மருந்துச்சீட்டு தயார்: ஆர்டர் #{id}',
    orderPlacingSuccess: 'ஆர்டர் #{id} வெற்றிகரமாகச் செய்யப்பட்டது!',
    orderConfirmedBy: '{name} உங்கள் ஆர்டரை உறுதிப்படுத்தியது! மருந்துகள் தயாரிக்கப்படுகின்றன.',
    orderPreparingAt: '{name} உங்கள் மருந்துகளைத் தயாரிக்கிறது. எ.நே: 25 நிமிடம்.',
    orderOutForDelivery: 'உங்கள் ஆர்டர் வழியில் உள்ளது! முகவர்: {name}. OTP: {otp}',
    orderDeliveredSuccess: 'ஆர்டர் வெற்றிகரமாக வழங்கப்பட்டது! நீங்கள் {points} விசுவாசப் புள்ளிகளைப் பெற்றீர்கள்! ★',
    orderCancelledBy: 'மருந்தகத்தால் ஆர்டர் ரத்து செய்யப்பட்டது. காரணம்: {reason}. முழுப் பணமும் திரும்பப் பெறப்படும்.',
    rxVerifiedSuccess: 'மருந்துச்சீட்டு சரிபார்க்கப்பட்டது! உங்கள் ஆர்டர் தயாரிக்கப்படுகிறது.',
    rxVerifiedReject: 'மருந்துச்சீட்டுப் பிரச்சனை: {reason}. தெளிவான புகைப்படத்தைப் பதிவேற்றவும்.',
    arrivalProximity: 'அருகாமை எச்சரிக்கை: விநியோக முகவர் 500மீ தூரத்தில் உள்ளார்! OTP: {otp}',
    newMissionAssigned: 'புதிய பொறுப்பு ஒதுக்கப்பட்டுள்ளது!',
    pickupReady: 'பிக்கப் தயார்: ஆர்டர் #{id}',
    sessionRevoked: 'அமர்வு ரத்து செய்யப்பட்டது: கணக்கு முனையம் ஆஃப்லைனில் உள்ளது.',
    identitySynced: 'அடையாளம் ஒத்திசைக்கப்பட்டது: மண்டலம் சரிபார்க்கப்பட்டது.',
    rxRemoved: 'மருத்துவ முனை அகற்றப்பட்டது',
    rxDeleteError: 'நீக்குதல் நெறிமுறை தோல்வியடைந்தது',
    syncedStatus: 'ஒத்திசைக்கப்பட்டது: {size}MB',
    pharmacyEnclaveNode: 'மருந்தக பெட்டக முனை',

    // Pharmacist Dashboard
    incomingPayloads: 'உள்வரும் சுமைகள்',
    preparatorySync: 'தயாரிப்பு ஒத்திசைவு',
    logisticsDeparture: 'விநியோகப் புறப்பாடு',
    districtRevenue: 'மாவட்ட வருவாய்',
    pharmacy: 'மருந்தகம்',
    enclaveNode: 'பெட்டக முனை',
    liveClinicalTerminal: 'நேரடி மருத்துவ முனையம் செயலிலுள்ளது',
    apolloHub: 'அப்போலோ மருந்தக மையம்',
    administratorNode: 'நிர்வாகி முனை: செயலில் உள்ளது',
    payloadManifest: 'சுமை மேனிஃபெஸ்ட் டெர்மினல்',
    realTime: 'நிகழ்நேரம்',
    districtHistory: 'மாவட்ட வரலாறு',
    terminalIdle: 'கிளினிக் டெர்மினல் செயலற்றது',
    uplinked: 'இணைக்கப்பட்டது',
    payloadId: 'சுமை ஐடி',
    anonymousNode: 'அடையாளமில்லாத முனை',
    karaikalEnclave: 'காரைக்கால் மண்டலம்',
    clinicalPayloadComponents: 'மருத்துவ சுமை கூறுகள்',
    medicineNode: 'மருந்து முனை',
    verifyAuthorization: 'மருத்துவ அங்கீகாரத்தை சரிபார்',
    acceptNode: 'முனை நெறிமுறையை ஏற்றுக்கொள்',
    rejectSync: 'ஒத்திசைவை நிராகரி',
    logNode: 'முனை பதிவேடு',
    preparatoryRedline: 'தயாரிப்பு ரெட்லைன்',
    assemblingPayload: 'சுமை வரிசைப்படுத்தப்படுகிறது...',
    dispatchPulse: 'டிஸ்பாட்ச் பல்ஸை இயக்கு',
    terminalLock: 'டெர்மினல் நெறிமுறை பூட்டு',
    emergencySecureMode: 'அவசர பாதுகாப்பு முறை: செயலில் உள்ளது',
    enterEnigma: 'எனிக்மா குறியீட்டை உள்ளிடவும்',
    realTimeChannels: 'நிகழ்நேர சேனல்கள்',
    patientHandover: 'நோயாளி ஒப்படைப்பு',
    districtAdmin: 'மாவட்ட நிர்வாகம்',
    nodeSynchronized: 'முனை ஒத்திசைக்கப்பட்டது',
    protocolSyncFailed: 'நெறிமுறை தோல்வியடைந்தது',
    inventoryArchitecture: 'இருப்பு கட்டமைப்பு',
    liveEnclaveInventorySync: 'நேரடி இருப்பு ஒத்திசைவு',
    stockVelocity: 'இருப்பு வேகம்',
    enclaveRisk: 'மண்டல ஆபத்து',
    criticalLowNodesDistrict: 'மாவட்டத்தில் சிக்கலான முனைகள் கண்டறியப்பட்டுள்ளன',
    replenishmentEfficiency: 'நிரப்புதல் நெறிமுறை திறன் அதிகரிப்பு',
    searchInventoryPlaceholder: 'மருந்து பெயர் அல்லது பொதுவான கலவை மூலம் தேடுங்கள்...',
    categoryArchitecture: 'வகை கட்டமைப்பு',
    pulseDemand: 'தேவை துடிப்பு',
    registryMetrics: 'பதிவேடு அளவீடுகள்',
    batchArchitectureNode: 'தொகுதி கட்டடக்கலை முனை',
    editNode: 'முனையைத் திருத்து',
    medicineRemovedInventory: 'இருப்புப் பட்டியலிலிருந்து மருந்து அகற்றப்பட்டது',
    replenishmentProtocol: 'நிரப்புதல் நெறிமுறை',
    stockMatrixUnits: 'இருப்பு மேட்ரிக்ஸ் அலகுகள்',
    authorizeRegistry: 'பதிவேட்டை அங்கீகரிக்கவும்',
    financialEnclave: 'நிதி பெட்டகம்',
    monthlyRevenueProtocol: 'மாதாந்திர வருவாய் நெறிமுறை',
    enclaveGrowth: 'பெட்டக வளர்ச்சி',
    orderFlowArchitecture: 'ஆர்டர் ஓட்ட கட்டடக்கலை',
    realTimeStreamProtocol: 'நிகழ்நேர ஓட்ட நெறிமுறை',
    resourceNodeProtocol: 'வள முனை நெறிமுறை',
    medicineNamePlaceholder: 'அறிவியல் மருந்து பெயர் (உதாரணம்: பாராசிட்டமால் 500 மிகி)',
    genericCodePlaceholder: 'செயலில் உள்ள வேதியியல் குறியீடு',
    nodeValuation: 'முனை மதிப்பு',
    totalUnits: 'மொத்த அலகுகள்',
    unitFormat: 'வடிவம் (பேக்ஸ் / விஎல்)',
    newMedicineSyncSuccess: 'புதிய மருத்துவக் கட்டமைப்பு ஒத்திசைக்கப்பட்டது!',
    therapeuticIdentification: 'சிகிச்சை அடையாளம்',
    manufacturingBrand: 'உற்பத்தி பிராண்ட்',

    // Blog & Articles
    articleNotFound: 'கட்டுரை விவரங்கள் கிடைக்கவில்லை',
    backToBlog: 'மீண்டும் வலைப்பதிவிற்கு',
    saveArticle: 'கட்டுரையைச் சேமிக்கவும்',
    shareArticle: 'கட்டுரையைப் பகிரவும்',
    updateDate: 'புதுப்பிக்கப்பட்டது',
    recommended: 'பரிந்துரைக்கப்படுபவை',
    instantConsult: 'உடனடி ஆலோசனை',
    copyLinkSuccess: 'இணைப்பு நகலெடுக்கப்பட்டது!',
    needSupport: 'மருத்துவ உதவி வேண்டுமா?',
    bookConsultantNow: 'ஆலோசனையை இப்போதே பதிவு செய்',
    navigation: 'வழிசெலுத்தல்',
    overview: 'மேலோட்டம்',
    primaryProtocol: 'முதன்மை நெறிமுறை',
    doctorAdvice: 'மருத்துவர் ஆலோசனை',
    conclusion: 'முடிவுரை',
    saveForLater: 'இதைச் சேமிக்க வேண்டுமா?',
    saveArticleDesc: 'இந்த மருத்துவத் தகவலை உங்கள் தனிப்பட்ட சுயவிவரத்தில் சேமிக்கவும்.',
    viewFullArchitecture: 'முழு கட்டமைப்பைப் பார்க்கவும்',
    consultArrow: 'ஆலோசனையைப் பெற →',

    // Shared UI
    enclaveSuffix: 'பெட்டகம்.',
    architectureSuffix: 'கட்டமைப்பு.',
    syncingEnclave: 'பெட்டகம் ஒத்திசைக்கப்படுகிறது...',
    verifiedAuthority: 'சரிபார்க்கப்பட்ட அதிகாரம்',
    tabMedicines: 'மருந்துகள்',
    tabAbout: 'விவரம்',
    tabReviews: 'மதிப்பாய்வுகள்',
    tabOffers: 'சலுகைகள்',

    // Hospitals
    districtArchitectureHeader: 'மாவட்ட கட்டடக்கலை',

    // Offers
    todaysBestOffers: 'காரைக்காலின் இன்றைய சிறந்த சலுகைகள்.',
    offersHeroDesc: '12+ காரைக்கால் மாவட்ட மருந்தகங்களிலிருந்து பிரத்யேக மருத்துவ கட்டடக்கலை ஒப்பந்தங்கள்.',
    flashSaleArch: 'பிளாஷ் விற்பனை கட்டடக்கலை',
    discountVitamins: 'அனைத்து வைட்டமின் சப்ளிமெண்ட்ஸுக்கும் 20% தள்ளுபடி',
    timeRemaining: 'மீதமுள்ள நேரம்',
    shopAllVitamins: 'அனைத்து வைட்டமின்களையும் வாங்கவும்',
    copyCodeLabel: 'குறியீட்டை நகலெடு',
    viewProduct: 'தயாரிப்பைப் பார்க்கவும்',
    globalArchCodes: 'உலகளாவிய கட்டடக்கலை குறியீடுகள்',
    activePharmacyVouchers: 'அனைத்து காரைக்கால் மாவட்ட குடியிருப்பாளர்களுக்கும் செயலில் உள்ள மருந்தக வவுச்சர்கள்.',
    codeCopied: 'குறியீடு நகலெடுக்கப்பட்டது! கட்டடக்கலை தயாராக உள்ளது.',

    // Emergency & Command Bar
    emergency: 'அவசரம்',
    emergencyHub: 'அவசர சிகிச்சை மையம்',
    priorityProtocolActive: 'முன்னுரிமை நெறிமுறை செயலில் உள்ளது',
    call108Emergency: '108 அவசர அழைப்பு',
    instantAmbulanceSync: 'உடனடி ஆம்புலன்ஸ் ஒத்திசைவு',
    bloodRequest: 'இரத்த வேண்டுகோள்',
    districtBloodHub: 'மாவட்ட இரத்த மையம்',
    oxygenPulse: 'ஆக்ஸிஜன் துடிப்பு',
    liveSupplyLink: 'நேரடி விநியோக இணைப்பு',
    sosSupport: 'SOS ஆதரவு',
    whatsappEnclave: 'வாட்ஸ்அப் பெட்டகம்',
    systemAuthorizedRapidResponse: 'அங்கீகரிக்கப்பட்ட விரைவான பதில்',
    searchNode: 'முனையைத் தேடுங்கள்...',
    districtProtocolSync: 'மாவட்ட நெறிமுறை ஒத்திசைவு',
    systemOnlineSynchronized: 'அமைப்பு ஆன்லைனில் ஒத்திசைக்கப்பட்டது',
    activeDeliveries: '{count} நேரடி விநியோகங்கள்',
    nodeTerminalsOnline: '{count} முனையங்கள் ஆன்லைனில் உள்ளன',
    pressEscToExit: 'வெளியேற ESC ஐ அழுத்தவும்',
    searchMedicineNode: 'மருந்து முனையைத் தேடு',
    scanDistrictInventoryClusters: 'மாவட்ட இருப்புத் தொகுப்புகளை ஸ்கேன் செய்யவும்',
    locateTerminalNodes: 'முனையங்களைக் கண்டறியவும்',
    findVerifiedRegionalPharmacies: 'சரிபார்க்கப்பட்ட பிராந்திய மருந்தகங்களைக் கண்டறியவும்',
    logisticsTelemetry: 'விநியோகத் தகவல்',
    trackActiveDeliveryStreams: 'நேரடி விநியோக ஓட்டங்களைக் கண்காணிக்கவும்',
    teleconsultPulse: 'தொலைநிலை கலந்தாய்வு துடிப்பு',
    syncWithCertifiedClinicians: 'சான்றளிக்கப்பட்ட மருத்துவர்களுடன் ஒத்திசைக்கவும்',
    medicalVault: 'மருத்துவப் பெட்டகம்',
    accessEncryptedPrescriptions: 'மறைக்குறியிடப்பட்ட மருந்துச்சீட்டுகளை அணுகவும்',
    systemHealth: 'அமைப்பின் ஆரோக்கியம்',
    districtArchitectureStatus: 'மாவட்ட கட்டமைப்பின் நிலை',
    searchMedicines: 'மருந்துகளைத் தேடு',
    viewCart: 'கூடையைப் பார்க்கவும்'
  }
};

const LanguageContext = createContext();

const getSafeLang = () => {
  try {
    return localStorage.getItem('medireach_lang') || 'en';
  } catch (e) {
    return 'en';
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(getSafeLang());

  useEffect(() => {
    try {
      localStorage.setItem('medireach_lang', lang);
    } catch (e) {}
  }, [lang]);

  const t = (key, params = {}) => {
    try {
      if (!translations[lang]) return key;
      let str = translations[lang][key] || key;
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
      return str;
    } catch (e) {
      console.error('Translation error:', e);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
