import { connectDB } from './config/db.js';
console.log('DB ok');
import { initSocket } from './config/socket.js';
console.log('Socket ok');
import authRoutes from './routes/authRoutes.js';
console.log('Auth ok');
import userRoutes from './routes/userRoutes.js';
console.log('User ok');
import medicineRoutes from './routes/medicineRoutes.js';
console.log('Medicine ok');
import pharmacyRoutes from './routes/pharmacyRoutes.js';
console.log('Pharmacy ok');
import orderRoutes from './routes/orderRoutes.js';
console.log('Order ok');
import prescriptionRoutes from './routes/prescriptionRoutes.js';
console.log('Prescription ok');
import appointmentRoutes from './routes/appointmentRoutes.js';
console.log('Appointment ok');
import adminRoutes from './routes/adminRoutes.js';
console.log('Admin ok');
import notificationRoutes from './routes/notificationRoutes.js';
console.log('Notification ok');
import paymentRoutes from './routes/paymentRoutes.js';
console.log('Payment ok');
import couponRoutes from './routes/couponRoutes.js';
console.log('Coupon ok');
import { errorHandler, notFound } from './middleware/errorHandler.js';
console.log('Handlers ok');
console.log('ALL IMPORTS OK');
