export const medicines = [
  {
    id: 'med-1',
    name: 'Paracetamol 500mg',
    brand: 'Calpol by GSK',
    generic: 'Acetaminophen 500mg',
    category: 'Tablets',
    price: 45,
    mrp: 60,
    discount: 25,
    stock: 'available',
    stockCount: 85,
    requiresRx: false,
    rating: 4.7,
    pharmacyId: 'ph-1',
    pharmacyName: 'Apollo Pharmacy',
    type: 'Tablet',
    description: 'Relief of mild to moderate pain and fever. Effective for headaches and body aches.',
    dosage: '1-2 tablets every 4-6 hours. Max 8 in 24hrs.',
    storage: 'Store below 25°C.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-2',
    name: 'Dolo 650',
    brand: 'Micro Labs',
    generic: 'Acetaminophen 650mg',
    category: 'Tablets',
    price: 32,
    mrp: 40,
    discount: 20,
    stock: 'available',
    stockCount: 154,
    requiresRx: false,
    rating: 4.8,
    pharmacyId: 'ph-3',
    pharmacyName: 'Sri Murugan Medical Store',
    type: 'Tablet',
    description: 'High-intensity antipyretic for fever management.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-3',
    name: 'Benadryl Cough Syrup',
    brand: 'J&J',
    generic: 'Diphenhydramine',
    category: 'Syrups',
    price: 105,
    mrp: 125,
    discount: 16,
    stock: 'available',
    stockCount: 60,
    requiresRx: false,
    rating: 4.4,
    pharmacyId: 'ph-2',
    pharmacyName: 'MedPlus Pharmacy',
    type: 'Syrup',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-4',
    name: 'Covishield Booster',
    brand: 'Serum Institute',
    generic: 'COVID-19 Vaccine',
    category: 'Vaccines',
    price: 780,
    mrp: 900,
    discount: 13,
    stock: 'available',
    stockCount: 24,
    requiresRx: true,
    rating: 4.9,
    pharmacyId: 'ph-8',
    pharmacyName: 'Karaikal Central Pharmacy',
    type: 'Vial',
    description: 'Third dose booster for COVID-19 protective protocol.',
    images: ['/assets/vaccine_pro.png']
  },
  {
    id: 'med-5',
    name: 'Himalaya Liv.52',
    brand: 'Himalaya',
    generic: 'Herbal Supplement',
    category: 'Ayurvedic',
    price: 150,
    mrp: 180,
    discount: 16,
    stock: 'available',
    stockCount: 200,
    requiresRx: false,
    rating: 4.8,
    pharmacyId: 'ph-5',
    pharmacyName: 'Sri Dhanvantri Medicals',
    type: 'Tablet',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-6',
    name: 'Amoxicillin 500mg',
    brand: 'Novamox',
    generic: 'Amoxicillin',
    category: 'Antibiotics',
    price: 85,
    mrp: 110,
    discount: 22,
    stock: 'available',
    stockCount: 45,
    requiresRx: true,
    rating: 4.6,
    pharmacyId: 'ph-1',
    pharmacyName: 'Apollo Pharmacy',
    type: 'Capsule',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-7',
    name: 'Vitamin C 500mg',
    brand: 'Limcee',
    generic: 'Ascorbic Acid',
    category: 'Vitamins',
    price: 25,
    mrp: 35,
    discount: 28,
    stock: 'available',
    stockCount: 1000,
    requiresRx: false,
    rating: 4.7,
    pharmacyId: 'ph-2',
    pharmacyName: 'MedPlus Pharmacy',
    type: 'Chewable',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-8',
    name: 'Combiflam',
    brand: 'Sanofi',
    generic: 'Ibuprofen + Paracetamol',
    category: 'Tablets',
    price: 65,
    mrp: 85,
    discount: 23,
    stock: 'low',
    stockCount: 8,
    requiresRx: false,
    rating: 4.5,
    pharmacyId: 'ph-3',
    pharmacyName: 'Sri Murugan Medical Store',
    type: 'Tablet',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-9',
    name: 'Volini Gel 50g',
    brand: 'Sun Pharma',
    generic: 'Pain Relief Gel',
    category: 'Pain Relief',
    price: 145,
    mrp: 170,
    discount: 15,
    stock: 'available',
    stockCount: 120,
    requiresRx: false,
    rating: 4.8,
    pharmacyId: 'ph-4',
    pharmacyName: 'MK Medical Store',
    type: 'Gel',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-10',
    name: 'Zincovit',
    brand: 'Apex',
    generic: 'Multivitamin + Zinc',
    category: 'Vitamins',
    price: 110,
    mrp: 135,
    discount: 18,
    stock: 'available',
    stockCount: 88,
    requiresRx: false,
    rating: 4.6,
    pharmacyId: 'ph-6',
    pharmacyName: 'Life Care Medicals',
    type: 'Tablet',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-11',
    name: 'Digene Mint 200ml',
    brand: 'Abbott',
    generic: 'Antacid',
    category: 'Syrups',
    price: 165,
    mrp: 195,
    discount: 15,
    stock: 'available',
    stockCount: 54,
    requiresRx: false,
    rating: 4.5,
    pharmacyId: 'ph-7',
    pharmacyName: 'Grace Pharmacy',
    type: 'Syrup',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-12',
    name: 'Insulin Pen',
    brand: 'Lantus',
    generic: 'Insulin Glargine',
    category: 'Diabetes',
    price: 650,
    mrp: 780,
    discount: 16,
    stock: 'available',
    stockCount: 12,
    requiresRx: true,
    rating: 4.9,
    pharmacyId: 'ph-8',
    pharmacyName: 'Karaikal Central Pharmacy',
    type: 'Injection',
    images: ['/assets/medicine_default.png']
  }
];

export const pharmacies = [
  { 
    id: 'ph-1', 
    name: 'Apollo Pharmacy', 
    location: '14, New Colony Road, Karaikal', 
    area: 'Karaikal Town',
    phone: '+91 94432 11111',
    timings: '8:00 AM – 10:00 PM',
    status: 'OPEN NOW',
    rating: 4.7, 
    deliveryFee: 30,
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Home Delivery', 'Prescription', 'UPI']
  },
  { 
    id: 'ph-2', 
    name: 'MedPlus Pharmacy', 
    location: '7, Collectorate Street, Karaikal', 
    area: 'Karaikal Town',
    phone: '+91 94432 22222',
    status: 'OPEN NOW',
    rating: 4.5, 
    deliveryFee: 40,
    verified: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Home Delivery', 'Card Payment']
  },
  { 
    id: 'ph-3', 
    name: 'Sri Murugan Medical Store', 
    location: 'Near New Bus Stand, Karaikal', 
    area: 'Karaikal Town',
    phone: '+91 94432 33333',
    status: 'OPEN NOW',
    rating: 4.9, 
    deliveryFee: 0,
    verified: true,
    is24hr: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Home Delivery', 'COD', '24/7']
  },
  { 
    id: 'ph-4', 
    name: 'MK Medical Store', 
    location: '23, Nagore Road, Karaikal', 
    area: 'Nagore Road',
    status: 'OPEN NOW',
    rating: 4.4, 
    deliveryFee: 25,
    verified: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Home Delivery', 'UPI']
  },
  { 
    id: 'ph-5', 
    name: 'Sri Dhanvantri Medicals', 
    location: '5, T.V.Koil Street, Karaikal', 
    area: 'Karaikal Town',
    status: 'OPEN NOW',
    rating: 4.3, 
    verified: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Ayurvedic Specialist']
  },
  { 
    id: 'ph-6', 
    name: 'Life Care Medicals', 
    location: '18, Poompuhar Street, Karaikal', 
    area: 'Poompuhar',
    status: 'OPEN NOW',
    rating: 4.6, 
    verified: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Baby Care']
  },
  { 
    id: 'ph-7', 
    name: 'Grace Pharmacy', 
    location: 'Keezhavur Main Road, Nagore', 
    area: 'Nagore',
    status: 'OPEN NOW',
    rating: 4.8, 
    verified: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['All Vaccines']
  },
  { 
    id: 'ph-8', 
    name: 'Karaikal Central Pharmacy', 
    location: 'Market Road, Karaikal', 
    area: 'Karaikal Town',
    status: 'OPEN 24HR',
    rating: 4.7, 
    verified: true,
    is24hr: true,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Emergency Sync', 'Night Delivery']
  },
  {
    id: 'ph-9',
    name: 'Neravy Medicals',
    location: 'Main Road, Neravy',
    area: 'Neravy',
    status: 'OPEN NOW',
    rating: 4.4,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Local Node']
  },
  {
    id: 'ph-10',
    name: 'TRS Pharma',
    location: 'Villianur Road, Karaikal',
    area: 'Keezhavur',
    status: 'OPEN NOW',
    rating: 4.6,
    images: ['/assets/pharmacy_pro.png'],
    services: ['Surgical Items']
  }
];

export const doctors = [
  {
    id: 'dr-1',
    name: 'Dr. S. Priya Raman',
    image: '/assets/doctor_pro.png',
    spec: 'General Physician',
    qual: 'MBBS, MD',
    hospital: 'Govt. General Hospital',
    experience: 12,
    fee: 200,
    status: 'online',
    rating: 4.8,
    bio: 'Senior consultant at GGH specializing in internal medicine and chronic conditions.',
    education: [{ degree: 'MBBS', institute: 'JIPMER' }],
    languages: ['Tamil', 'English'],
    schedule: { days: 'Mon - Sat', slots: ['09:00 AM', '11:00 AM', '04:00 PM', '06:00 PM'] }
  },
  {
    id: 'dr-2',
    name: 'Dr. K. Anand Kumar',
    image: '/assets/doctor_pro.png',
    spec: 'Cardiologist',
    qual: 'MBBS, MD, DM',
    hospital: 'Karaikal Cardiac Centre',
    experience: 18,
    fee: 500,
    status: 'online',
    rating: 4.9,
    bio: 'Expert in non-invasive cardiology and management of complex heart rhythms.',
    education: [{ degree: 'DM Cardiology', institute: 'AIIMS' }],
    languages: ['Tamil', 'English', 'Hindi'],
    schedule: { days: 'Mon - Fri', slots: ['10:00 AM', '12:00 PM', '05:00 PM'] }
  },
  {
    id: 'dr-3',
    name: 'Dr. M. Meena Krishnan',
    image: '/assets/doctor_pro.png',
    spec: 'Paediatrician',
    qual: 'MBBS, DCH',
    hospital: 'Child Care Hospital',
    experience: 10,
    fee: 300,
    status: 'busy',
    rating: 4.7,
    bio: 'Specialist in newborn intensive care and developmental milestones.',
    education: [{ degree: 'DCH', institute: 'ICH Chennai' }],
    languages: ['Tamil', 'English'],
    schedule: { days: 'Mon - Sat', slots: ['09:30 AM', '10:30 AM', '04:30 PM'] }
  },
  {
    id: 'dr-9',
    name: 'Dr. G. Sivakumar',
    image: '/assets/doctor_pro.png',
    spec: 'Neurologist',
    qual: 'MBBS, MD, DM',
    hospital: 'Karaikal Neuro Centre',
    experience: 16,
    fee: 600,
    status: 'online',
    rating: 4.9,
    bio: 'Specialist in neuro-rehabilitation and complex seizure management.',
    education: [{ degree: 'DM Neurology', institute: 'JIPMER' }],
    languages: ['Tamil', 'English'],
    schedule: { days: 'Mon - Fri', slots: ['10:00 AM', '04:00 PM'] }
  },
  {
    id: 'dr-10',
    name: 'Dr. A. Kavitha',
    image: '/assets/doctor_pro.png',
    spec: 'Psychiatrist',
    qual: 'MBBS, MD',
    hospital: 'Mind Care Clinic',
    experience: 11,
    fee: 450,
    status: 'online',
    rating: 4.8,
    bio: 'Dedicated psychiatrist focusing on integrated mental wellness.',
    education: [{ degree: 'MD Psychiatry', institute: 'NIMHANS' }],
    languages: ['Tamil', 'English', 'Malayalam'],
    schedule: { days: 'Mon - Sat', slots: ['11:00 AM', '05:00 PM'] }
  },
  {
    id: 'dr-11',
    name: 'Dr. S. Manikandan',
    image: '/assets/doctor_pro.png',
    spec: 'Pulmonologist',
    qual: 'MBBS, MD',
    hospital: 'GGH Pulmonology Unit',
    experience: 14,
    fee: 350,
    status: 'busy',
    rating: 4.7,
    bio: 'Expert in respiratory medicine and critical care pulmonary medicine.',
    education: [{ degree: 'MD Pulmonology', institute: 'MMC' }],
    languages: ['Tamil', 'English'],
    schedule: { days: 'Tue - Sat', slots: ['09:00 AM', '03:00 PM'] }
  },
  {
    id: 'dr-12',
    name: 'Dr. J. Preethi',
    image: '/assets/doctor_pro.png',
    spec: 'Dentist',
    qual: 'BDS, MDS',
    hospital: 'Smile Dental Clinic',
    experience: 7,
    fee: 250,
    status: 'online',
    rating: 4.9,
    bio: 'Cosmetic dentist committed to pain-free dental procedures.',
    education: [{ degree: 'MDS Orthodontics', institute: 'Saveetha' }],
    languages: ['Tamil', 'English'],
    schedule: { days: 'Mon - Sat', slots: ['10:00 AM', '06:00 PM'] }
  }
];

export const hospitals = [
  {
    id: 'hosp-1',
    name: 'Govt. General Hospital',
    type: 'Government',
    emergency: '24hr Emergency',
    image: '/assets/hospital_pro.png',
    address: 'Hospital Road, Karaikal',
    phone: '04368-222288',
    beds: '300+',
    gps: { lat: 10.9250, lng: 79.8380 }
  },
  {
    id: 'hosp-2',
    name: 'JIPMER Karaikal',
    type: 'Teaching Hospital',
    emergency: '24hr Emergency',
    image: '/assets/hospital_pro.png',
    address: 'JIPMER Campus, Karaikal',
    phone: '04368-220500',
    beds: '150+',
    gps: { lat: 10.9320, lng: 79.8410 }
  },
  {
    id: 'hosp-3',
    name: 'Karaikal Cardiac Centre',
    type: 'Private',
    emergency: '24/7 Cardiac',
    image: '/assets/hospital_pro.png',
    address: 'New Colony, Karaikal',
    beds: '50+'
  }
];

export const blogPosts = [
  {
    id: 'blog-1',
    slug: 'essentials-karaikal-home',
    title: '5 Essentials for Every Karaikal Household',
    author: 'Dr. S. Priya Raman',
    date: '24 Mar 2026',
    category: 'Health Tips',
    image: '/assets/medicine_default.png'
  },
  {
    id: 'blog-2',
    slug: 'summer-health-tips',
    title: 'Staying Hydrated in the Karaikal Coastal Heat',
    author: 'Dr. K. Anand Kumar',
    date: '22 Mar 2026',
    category: 'Nutrition',
    image: '/assets/hospital_pro.png'
  }
];
