export const medicines = [
  {
    id: 'med-1',
    name: 'Paracetamol 500mg',
    brand: 'Calpol by GlaxoSmithKline',
    generic: 'Acetaminophen 500mg',
    category: 'Tablets',
    price: 45,
    mrp: 60,
    discount: 25,
    stock: 'available',
    stockCount: 85,
    soldCount: 1200,
    requiresRx: false,
    rating: 4.7,
    reviewsCount: 42,
    pharmacyId: 'ph-1',
    pharmacyName: 'Apollo Pharmacy',
    type: 'Tablet',
    description: 'Paracetamol 500mg is used for relief of mild to moderate pain and fever. Effective for headaches, toothaches, back pain, cold, flu, and general aches common in Karaikal district.',
    dosage: 'Adults: 1-2 tablets every 4-6 hours. Maximum 8 tablets in 24hrs. Take with food. Do not exceed recommended dose.',
    sideEffects: 'Rare: Liver damage with overdose, skin rash, nausea. Consult Dr. Priya Raman at Govt. General Hospital if symptoms persist.',
    storage: 'Store below 25°C. Keep away from moisture.',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-2',
    name: 'Dolo 650',
    brand: 'Micro Labs',
    generic: 'Paracetamol 650mg',
    category: 'Tablets',
    price: 30,
    mrp: 38,
    discount: 21,
    stock: 'available',
    stockCount: 154,
    soldCount: 3500,
    requiresRx: false,
    rating: 4.8,
    reviewsCount: 156,
    pharmacyId: 'ph-3',
    pharmacyName: 'Sri Murugan Medical Store',
    type: 'Tablet',
    description: 'Dolo 650 is a widely used antipyretic and analgesic for higher-intensity fever and pain management.',
    dosage: 'One tablet as needed, max 4 times daily.',
    sideEffects: 'Mild nausea, allergic reactions in rare cases.',
    storage: 'Keep in a cool, dry place.',
    manufacturer: 'Micro Labs Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-3',
    name: 'Benadryl Cough Syrup',
    brand: 'J&J',
    generic: 'Diphenhydramine',
    category: 'Syrups',
    price: 105,
    mrp: 120,
    discount: 12,
    stock: 'available',
    stockCount: 60,
    soldCount: 2200,
    requiresRx: false,
    rating: 4.4,
    reviewsCount: 210,
    pharmacyId: 'ph-2',
    pharmacyName: 'MedPlus Pharmacy',
    type: 'Syrup',
    description: 'Relieves cough and nasal congestion caused by common cold or allergies.',
    dosage: '10ml three times a day or as directed.',
    sideEffects: 'Drowsiness, dizziness, dry mouth.',
    storage: 'Protect from sunlight.',
    manufacturer: 'Johnson & Johnson',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-4',
    name: 'Covishield Booster',
    brand: 'Serum Institute',
    generic: 'COVID-19 Vaccine',
    category: 'Vaccines',
    price: 780,
    mrp: 900,
    discount: 13,
    stock: 'available',
    stockCount: 45,
    soldCount: 8500,
    requiresRx: true,
    rating: 4.9,
    reviewsCount: 1240,
    pharmacyId: 'ph-8',
    pharmacyName: 'Karaikal Central Pharmacy',
    type: 'Vial',
    description: 'Official booster dose for COVID-19 protection.',
    dosage: 'Single 0.5ml intramuscular injection.',
    sideEffects: 'Fever, soreness at injection site, fatigue.',
    storage: 'Refrigerate at 2-8°C. Do not freeze.',
    manufacturer: 'Serum Institute of India',
    images: ['/assets/vaccine_pro.png']
  },
  {
    id: 'med-5',
    name: 'Himalaya Liv.52',
    brand: 'Himalaya',
    generic: 'Herbal Supplement',
    category: 'Ayurvedic',
    price: 150,
    mrp: 175,
    discount: 14,
    stock: 'available',
    stockCount: 200,
    soldCount: 3100,
    requiresRx: false,
    rating: 4.8,
    reviewsCount: 450,
    pharmacyId: 'ph-5',
    pharmacyName: 'Sri Dhanvantri Medicals',
    type: 'Tablet',
    description: 'Natural hepatoprotective herbal preparation.',
    dosage: '2-3 tablets twice daily.',
    sideEffects: 'None reported if taken as recommended.',
    storage: 'Store in a cool place away from direct sunlight.',
    manufacturer: 'Himalaya Wellness Company',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-6',
    name: 'Baby Sunscreens',
    brand: 'Mamaearth',
    generic: 'Sunscreen',
    category: 'Baby Care',
    price: 299,
    mrp: 350,
    discount: 15,
    stock: 'available',
    stockCount: 120,
    soldCount: 450,
    requiresRx: false,
    rating: 4.7,
    reviewsCount: 88,
    pharmacyId: 'ph-4',
    pharmacyName: 'MK Medical Store',
    type: 'Cream',
    description: 'Gentle mineral-based sunscreen for babies.',
    dosage: 'Apply liberally 15 mins before sun exposure.',
    sideEffects: 'Rare skin irritation.',
    storage: 'Store at room temperature.',
    manufacturer: 'Honasa Consumer Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-7',
    name: 'Surgical Gloves',
    brand: 'Romsons',
    generic: 'Latex Gloves',
    category: 'Surgical',
    price: 450,
    mrp: 600,
    discount: 25,
    stock: 'available',
    stockCount: 500,
    soldCount: 120,
    requiresRx: false,
    rating: 4.5,
    reviewsCount: 34,
    pharmacyId: 'ph-6',
    pharmacyName: 'Life Care Medicals',
    type: 'Equipment',
    description: 'Sterile latex gloves for medical use.',
    dosage: 'Single use only.',
    sideEffects: 'Latex allergy if applicable.',
    storage: 'Store in cool, dry conditions.',
    manufacturer: 'Romsons Group',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-8',
    name: 'Vitamin C 500mg',
    brand: 'Limcee',
    generic: 'Ascorbic Acid',
    category: 'Vitamins',
    price: 25,
    mrp: 32,
    discount: 22,
    stock: 'available',
    stockCount: 1000,
    soldCount: 12000,
    requiresRx: false,
    rating: 4.8,
    reviewsCount: 560,
    pharmacyId: 'ph-1',
    pharmacyName: 'Apollo Pharmacy',
    type: 'Tablet',
    description: 'Essential vitamin C for immunity boost.',
    dosage: 'One chewable tablet daily.',
    sideEffects: 'None significant.',
    storage: 'Keep container tight.',
    manufacturer: 'Abbott India',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-9',
    name: 'Amoxicillin 500mg',
    brand: 'Novamox',
    generic: 'Amoxicillin',
    category: 'Antibiotics',
    price: 85,
    mrp: 110,
    discount: 23,
    stock: 'available',
    stockCount: 120,
    soldCount: 890,
    requiresRx: true,
    rating: 4.6,
    reviewsCount: 78,
    pharmacyId: 'ph-1',
    pharmacyName: 'Apollo Pharmacy',
    type: 'Capsule',
    description: 'Broad-spectrum antibiotic used to treat various bacterial infections.',
    dosage: 'As prescribed by the doctor. Typically 2 or 3 times daily.',
    sideEffects: 'Diarrhea, nausea, rash.',
    storage: 'Store at room temperature.',
    manufacturer: 'Cipla Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-10',
    name: 'Cetirizine 10mg',
    brand: 'Okacet',
    generic: 'Cetirizine',
    category: 'Tablets',
    price: 15,
    mrp: 20,
    discount: 25,
    stock: 'available',
    stockCount: 500,
    soldCount: 4500,
    requiresRx: false,
    rating: 4.7,
    reviewsCount: 134,
    pharmacyId: 'ph-2',
    pharmacyName: 'MedPlus Pharmacy',
    type: 'Tablet',
    description: 'Effective anti-allergic medication for hay fever and skin allergies.',
    dosage: 'One tablet daily at night.',
    sideEffects: 'Drowsiness, dry mouth.',
    storage: 'Store away from moisture.',
    manufacturer: 'Cipla Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-11',
    name: 'Combiflam',
    brand: 'Sanofi',
    generic: 'Ibuprofen + Paracetamol',
    category: 'Tablets',
    price: 65,
    mrp: 80,
    discount: 18,
    stock: 'low',
    stockCount: 12,
    soldCount: 5600,
    requiresRx: false,
    rating: 4.5,
    reviewsCount: 312,
    pharmacyId: 'ph-3',
    pharmacyName: 'Sri Murugan Medical Store',
    type: 'Tablet',
    description: 'Combination medicine for pain relief and inflammation.',
    dosage: 'One tablet three times daily after food.',
    sideEffects: 'Acidity, stomach pain.',
    storage: 'Cool dry place.',
    manufacturer: 'Sanofi India Ltd.',
    images: ['/assets/medicine_default.png']
  },
  {
    id: 'med-12',
    name: 'Insulin Glargine',
    brand: 'Lantus',
    generic: 'Insulin',
    category: 'Diabetes',
    price: 650,
    mrp: 750,
    discount: 13,
    stock: 'available',
    stockCount: 30,
    soldCount: 420,
    requiresRx: true,
    rating: 4.9,
    reviewsCount: 95,
    pharmacyId: 'ph-8',
    pharmacyName: 'Karaikal Central Pharmacy',
    type: 'Injection',
    description: 'Long-acting basal insulin for diabetes management.',
    dosage: 'As per doctor\'s prescription. Subcutaneous injection.',
    sideEffects: 'Hypoglycemia, injection site reactions.',
    storage: 'Refrigerate (2°C - 8°C). Do not freeze.',
    manufacturer: 'Sanofi',
    images: ['/assets/medicine_default.png']
  }
];

export const pharmacies = [
  { 
    id: 'ph-1', 
    name: 'Apollo Pharmacy', 
    location: '14, New Colony Road, Karaikal - 609602', 
    phone: '+91 94432 11111',
    gps: { lat: 10.9254, lng: 79.8380 },
    timings: '8:00 AM – 10:00 PM',
    status: 'OPEN',
    rating: 4.7, 
    reviewsCount: 234,
    deliveryFee: 30,
    freeThreshold: 500,
    distance: 0.8, 
    eta: '25-30 min',
    area: 'Karaikal Town',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 90, syrups: 85, vaccines: 45, injections: 80, baby: 88, ayurvedic: 25
    },
    alerts: ["Flu Vaccine \u2014 Out of Stock"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD']
  },
  { 
    id: 'ph-2', 
    name: 'MedPlus Pharmacy', 
    location: '7, Collectorate Street, Karaikal - 609602', 
    phone: '+91 94432 22222',
    gps: { lat: 10.9261, lng: 79.8365 },
    timings: '7:00 AM – 10:30 PM',
    status: 'OPEN',
    rating: 4.5, 
    reviewsCount: 178,
    deliveryFee: 40,
    freeThreshold: 300,
    distance: 1.2, 
    eta: '30-35 min',
    area: 'Karaikal Town',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 85, syrups: 55, vaccines: 90, injections: 50, baby: 82, ayurvedic: 45
    },
    alerts: ["Cetirizine Syrup \u2014 Only 3 left"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD', 'Wallet']
  },
  { 
    id: 'ph-3', 
    name: 'Sri Murugan Medical Store', 
    location: 'Near New Bus Stand, Karaikal - 609602', 
    phone: '+91 94432 33333',
    gps: { lat: 10.9241, lng: 79.8391 },
    timings: '6:00 AM \u2013 11:00 PM',
    status: 'OPEN',
    rating: 4.9, 
    reviewsCount: 312,
    deliveryFee: 0,
    freeThreshold: 0,
    distance: 0.5, 
    eta: '15-20 min',
    area: 'Karaikal Town',
    verified: true,
    is24hr: true,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 95, syrups: 92, vaccines: 28, injections: 90, baby: 55, ayurvedic: 85
    },
    alerts: ["Hepatitis B Vaccine \u2014 Only 8 doses left"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD'],
    isTopRated: true,
    isFastest: true
  },
  { 
    id: 'ph-4', 
    name: 'MK Medical Store', 
    location: '23, Nagore Road, Karaikal - 609602', 
    phone: '+91 94432 44444',
    gps: { lat: 10.9150, lng: 79.8450 },
    timings: '8:30 AM \u2013 9:30 PM',
    status: 'OPEN',
    rating: 4.4, 
    reviewsCount: 89,
    deliveryFee: 25,
    freeThreshold: 500,
    distance: 1.8, 
    eta: '35-40 min',
    area: 'Nagore Road',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 55, syrups: 22, vaccines: 0, injections: 45, baby: 28, ayurvedic: 42
    },
    alerts: ["Vaccines \u2014 Currently Unavailable", "Baby Care \u2014 Low Stock"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'COD']
  },
  { 
    id: 'ph-5', 
    name: 'Sri Dhanvantri Medicals', 
    location: '5, T.V.Koil Street, Karaikal - 609602', 
    phone: '+91 94432 55555',
    gps: { lat: 10.9310, lng: 79.8320 },
    timings: '9:00 AM \u2013 9:00 PM',
    status: 'OPEN',
    rating: 4.3, 
    reviewsCount: 67,
    deliveryFee: 30,
    freeThreshold: 500,
    distance: 2.2, 
    eta: '40-45 min',
    area: 'Karaikal Town',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 45, syrups: 48, vaccines: 0, injections: 28, baby: 92, ayurvedic: 95
    },
    alerts: ["Best Ayurvedic stock in Karaikal"],
    isAyurvedicSpecialist: true,
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD']
  },
  { 
    id: 'ph-6', 
    name: 'Life Care Medicals', 
    location: '18, Poompuhar Street, Karaikal - 609602', 
    phone: '+91 94432 66666',
    gps: { lat: 10.9200, lng: 79.8250 },
    timings: '8:00 AM \u2013 10:00 PM',
    status: 'OPEN',
    rating: 4.6, 
    reviewsCount: 145,
    deliveryFee: 20,
    freeThreshold: 300,
    distance: 1.5, 
    eta: '30-35 min',
    area: 'Poompuhar',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 88, syrups: 82, vaccines: 55, injections: 85, baby: 98, ayurvedic: 52
    },
    isBabyCareSpecialist: true,
    alerts: ["Best Baby Care stock in Karaikal"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD']
  },
  { 
    id: 'ph-7', 
    name: 'Grace Pharmacy', 
    location: 'Keezhavur Main Road, Nagore - 611002', 
    phone: '+91 94432 77777',
    gps: { lat: 10.8250, lng: 79.8450 },
    timings: '8:00 AM \u2013 9:00 PM',
    status: 'OPEN',
    rating: 4.8, 
    reviewsCount: 201,
    deliveryFee: 0,
    freeThreshold: 0,
    distance: 6.2, 
    eta: '45-55 min',
    area: 'Nagore',
    verified: true,
    is24hr: false,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 92, syrups: 88, vaccines: 95, injections: 55, baby: 90, ayurvedic: 22
    },
    alerts: ["All vaccines available \u2713"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD']
  },
  { 
    id: 'ph-8', 
    name: 'Karaikal Central Pharmacy', 
    location: 'Market Road, Karaikal - 609602', 
    phone: '+91 94432 88888',
    gps: { lat: 10.9230, lng: 79.8375 },
    timings: 'OPEN 24 HOURS',
    status: 'OPEN 24HR',
    rating: 4.7, 
    reviewsCount: 289,
    deliveryFee: 30,
    freeThreshold: 400,
    distance: 1.0, 
    eta: '25-30 min',
    area: 'Karaikal Town',
    verified: true,
    is24hr: true,
    images: ['/assets/pharmacy_pro.png'],
    stock: {
      tablets: 90, syrups: 85, vaccines: 82, injections: 88, baby: 85, ayurvedic: 55
    },
    alerts: ["Best choice for midnight/emergency orders"],
    services: ['Home Delivery', 'Prescription', 'UPI', 'Card', 'COD']
  }
];

export const doctors = [
  {
    id: 'dr-1',
    name: 'Dr. S. Priya Raman',
    image: '/assets/doctor_pro.png',
    spec: 'General Physician',
    qual: 'MBBS, MD',
    hospital: 'Govt. General Hospital, Karaikal',
    experience: 12,
    languages: ['Tamil', 'English'],
    fee: 200,
    status: 'online',
    nextAvailable: 'Today 4PM',
    rating: 4.8,
    consultations: 312,
    tags: ['Fever', 'Cold', 'Diabetes', 'Hypertension', 'General'],
    bio: 'Dr. Priya Raman is a senior consultant at Govt. General Hospital, Karaikal, specializing in internal medicine and chronic conditions like diabetes and hypertension. She has been serving the Karaikal community for over a decade.',
    education: [
      { degree: 'MBBS', institute: 'JIPMER, Puducherry' },
      { degree: 'MD General Medicine', institute: 'Madras Medical College' }
    ],
    registration: 'TNM-XXXXX',
    schedule: {
      days: 'Mon - Sat',
      slots: ['09:00 AM', '10:00 AM', '11:00 AM', '04:00 PM', '05:00 PM', '06:00 PM']
    }
  },
  {
    id: 'dr-2',
    name: 'Dr. K. Anand Kumar',
    image: '/assets/doctor_pro.png',
    spec: 'Cardiologist',
    qual: 'MBBS, MD, DM Cardiology',
    hospital: 'Karaikal Cardiac Care Centre, New Colony',
    experience: 18,
    languages: ['Tamil', 'English', 'Hindi'],
    fee: 500,
    status: 'online',
    rating: 4.9,
    consultations: 189,
    tags: ['Heart Disease', 'Hypertension', 'Cholesterol', 'ECG'],
    bio: 'Expert in non-invasive cardiology and management of complex heart rhythm disorders.',
    education: [
      { degree: 'MBBS', institute: 'CMC Vellore' },
      { degree: 'MD', institute: 'Madras Medical College' },
      { degree: 'DM Cardiology', institute: 'AIIMS, Delhi' }
    ],
    registration: 'TNM-YYYYY',
    schedule: {
      days: 'Mon - Fri',
      slots: ['10:00 AM', '11:00 AM', '05:00 PM', '06:00 PM']
    }
  },
  {
    id: 'dr-3',
    name: 'Dr. M. Meena Krishnan',
    image: '/assets/doctor_pro.png',
    spec: 'Paediatrician',
    qual: 'MBBS, DCH',
    hospital: 'Child Care Hospital, Market Road, Karaikal',
    experience: 10,
    languages: ['Tamil', 'English'],
    fee: 300,
    status: 'busy',
    rating: 4.7,
    consultations: 245,
    tags: ['Vaccination', 'Newborn Care', 'Child Nutrition'],
    bio: 'Specialist in newborn intensive care and pediatric developmental milestones.',
    education: [
      { degree: 'MBBS', institute: 'Madurai Medical College' },
      { degree: 'DCH', institute: 'Inst. of Child Health, Chennai' }
    ],
    registration: 'TNM-ZZZZZ',
    schedule: {
      days: 'Mon - Sat',
      slots: ['09:30 AM', '10:30 AM', '04:30 PM', '05:30 PM']
    }
  },
  {
    id: 'dr-4',
    name: 'Dr. R. Suresh Prabhu',
    image: '/assets/doctor_pro.png',
    spec: 'Dermatologist',
    qual: 'MBBS, DVD',
    hospital: 'Skin & Hair Clinic, Karaikal',
    experience: 8,
    languages: ['Tamil', 'English'],
    fee: 350,
    status: 'offline',
    rating: 4.6,
    consultations: 156,
    tags: ['Acne', 'Hair Loss', 'Skin Surgery', 'Laser'],
    bio: 'Consultant Dermatologist focusing on advanced skin and hair treatments.',
    education: [
      { degree: 'MBBS', institute: 'Stanley Medical College' },
      { degree: 'DVD', institute: 'Madras Medical College' }
    ],
    registration: 'TNM-AAAAA',
    schedule: {
      days: 'Mon - Fri',
      slots: ['11:00 AM', '12:00 PM', '06:00 PM', '07:00 PM']
    }
  },
  {
    id: 'dr-5',
    name: 'Dr. V. Lakshmi Devi',
    image: '/assets/doctor_pro.png',
    spec: 'Gynaecologist',
    qual: 'MBBS, MS (OBG)',
    hospital: "Devi Women's Hospital, Nehru Street",
    experience: 15,
    languages: ['Tamil', 'English', 'Telugu'],
    fee: 400,
    status: 'online',
    rating: 4.9,
    consultations: 412,
    tags: ['Maternity', 'Infertility', 'PCOS', 'Surgery'],
    bio: 'Experienced Obstetrician and Gynaecologist managing high-risk pregnancies.',
    education: [
      { degree: 'MBBS', institute: 'KMC, Chennai' },
      { degree: 'MS OBG', institute: 'JIPMER' }
    ],
    registration: 'TNM-BBBBB',
    schedule: {
      days: 'Mon - Sat',
      slots: ['10:00 AM', '11:00 AM', '04:00 PM', '05:00 PM']
    }
  },
  {
    id: 'dr-6',
    name: 'Dr. T. Balasubramanian',
    image: '/assets/doctor_pro.png',
    spec: 'Orthopaedic',
    qual: 'MBBS, MS Ortho',
    hospital: 'Bone & Joint Clinic, Karaikal',
    experience: 20,
    languages: ['Tamil', 'English'],
    fee: 450,
    status: 'busy',
    rating: 4.8,
    consultations: 567,
    tags: ['Joint Replacement', 'Fractures', 'Spine Care'],
    bio: 'Veteran Orthopaedic Surgeon specializing in trauma and arthroplasty.',
    education: [
      { degree: 'MBBS', institute: 'Madras Medical College' },
      { degree: 'MS Ortho', institute: 'CMC Vellore' }
    ],
    registration: 'TNM-CCCCC',
    schedule: {
      days: 'Mon - Fri',
      slots: ['09:00 AM', '10:00 AM', '05:00 PM', '06:00 PM']
    }
  },
  {
    id: 'dr-7',
    name: 'Dr. P. Rajesh Kannan',
    image: '/assets/doctor_pro.png',
    spec: 'ENT Specialist',
    qual: 'MBBS, DLO',
    hospital: 'ENT Care Centre, Karaikal',
    experience: 9,
    languages: ['Tamil', 'English'],
    fee: 300,
    status: 'online',
    rating: 4.6,
    consultations: 178,
    tags: ['Sinus', 'Hearing Loss', 'Thyroid', 'Snoring'],
    bio: 'ENT Consultant with a focus on microsurgery and allergy management.',
    education: [
      { degree: 'MBBS', institute: 'Annamalai University' },
      { degree: 'DLO', institute: 'Madras Medical College' }
    ],
    registration: 'TNM-DDDDD',
    schedule: {
      days: 'Mon - Sat',
      slots: ['10:30 AM', '11:30 AM', '04:30 PM', '05:30 PM']
    }
  },
  {
    id: 'dr-8',
    name: 'Dr. N. Vijayalakshmi',
    image: '/assets/doctor_pro.png',
    spec: 'Ophthalmologist',
    qual: 'MBBS, MS Ophthalmology',
    hospital: 'Eye Care Hospital, Karaikal',
    experience: 14,
    languages: ['Tamil', 'English'],
    fee: 350,
    status: 'online',
    rating: 4.7,
    consultations: 289,
    tags: ['Cataract', 'Lasik', 'Glaucoma', 'Eyecare'],
    bio: 'Specialist in laser vision correction and geriatric eye care.',
    education: [
      { degree: 'MBBS', institute: 'Chengalpattu Medical College' },
      { degree: 'MS Ophthalmology', institute: 'RIO GOH, Chennai' }
    ],
    registration: 'TNM-EEEEE',
    schedule: {
      days: 'Mon - Sat',
      slots: ['09:00 AM', '10:00 AM', '03:00 PM', '04:00 PM']
    }
  }
];

export const hospitals = [
  {
    id: 'hosp-1',
    name: 'Govt. General Hospital Karaikal',
    type: 'Government',
    emergency: '24hr Emergency',
    image: '/assets/hospital_pro.png',
    address: 'Hospital Road, Karaikal - 609602',
    phone: '04368-222288',
    emergencyPhone: '108',
    departments: ['General Medicine', 'Surgery', 'Pediatrics', 'Obstetrics', 'Orthopedics', 'E.N.T'],
    beds: '300+',
    accreditation: 'NABH Accredited',
    gps: { lat: 10.9250, lng: 79.8380 }
  },
  {
    id: 'hosp-2',
    name: 'JIPMER Karaikal Campus',
    type: 'Teaching Hospital',
    emergency: '24hr Emergency',
    image: '/assets/hospital_pro.png',
    address: 'JIPMER Campus Road, Karaikal',
    phone: '04368-220500',
    departments: ['Advanced Diagnostics', 'Specialist Care', 'Research Unit', 'Cardiology'],
    beds: '150+',
    accreditation: 'National Importance',
    gps: { lat: 10.9320, lng: 79.8410 }
  },
  {
    id: 'hosp-3',
    name: 'Karaikal Cardiac Care Centre',
    type: 'Private',
    emergency: 'Cardiac Emergency 24/7',
    image: '/assets/hospital_pro.png',
    address: 'New Colony, Karaikal',
    phone: '04368-223344',
    departments: ['Cardiology', 'Cardio-thoracic Surgery', 'ICU', 'ECG/Echo'],
    beds: '50+',
    accreditation: 'ISO Certified',
    gps: { lat: 10.9260, lng: 79.8395 }
  },
  {
    id: 'hosp-4',
    name: "Devi Women's Hospital",
    type: 'Private',
    emergency: 'Maternity Emergency 24/7',
    image: '/assets/hospital_pro.png',
    address: 'Nehru Street, Karaikal',
    phone: '04368-224455',
    departments: ['Gynaecology', 'Obstetrics', 'NICU', 'Infertility Center'],
    beds: '40+',
    accreditation: 'State Level',
    gps: { lat: 10.9240, lng: 79.8370 }
  },
  {
    id: 'hosp-5',
    name: 'Child Care Hospital',
    type: 'Private',
    emergency: 'Pediatric Emergency 24/7',
    image: '/assets/hospital_pro.png',
    address: 'Market Road, Karaikal',
    phone: '04368-225566',
    departments: ['Paediatrics', 'Neonatology', 'Immunization', 'Child Surgery'],
    beds: '30+',
    accreditation: 'State Level',
    gps: { lat: 10.9230, lng: 79.8360 }
  }
];

export const blogPosts = [
  {
    id: 'blog-1',
    slug: 'essentials-karaikal-home',
    title: '5 Essentials for Every Karaikal Household',
    excerpt: 'Keeping your health synchronized with the district architecture requires a few key essentials. From hydration protocols to emergency node access...',
    author: 'Dr. S. Priya Raman',
    authorHospital: 'Govt. General Hospital, Karaikal',
    date: '24 Mar 2026',
    readTime: '5 min read',
    category: 'Health Tips',
    image: '/assets/medicine_default.png'
  },
  {
    id: 'blog-2',
    slug: 'summer-health-tips',
    title: 'Staying Hydrated in the Karaikal Coastal Heat',
    excerpt: 'How to manage thermal architecture impacts on health during the upcoming summer peak in the coastal enclave...',
    author: 'Dr. K. Anand Kumar',
    authorHospital: 'Karaikal Cardiac Care Centre',
    date: '22 Mar 2026',
    readTime: '4 min read',
    category: 'Nutrition',
    image: '/assets/hospital_pro.png'
  },
  {
    id: 'blog-3',
    slug: 'diabetes-management-at-home',
    title: 'Precision Diabetes Management: A Node Tutorial',
    excerpt: 'Synchronizing your glucose monitoring with the MediPharm enclave for real-time district-wide health updates...',
    author: 'Dr. S. Priya Raman',
    authorHospital: 'Govt. General Hospital, Karaikal',
    date: '20 Mar 2026',
    readTime: '8 min read',
    category: 'Medicine Guide',
    image: '/assets/medicine_default.png'
  },
  {
    id: 'blog-4',
    slug: 'karaikal-medical-infrastructure-2026',
    title: 'The Future of Medical Architecture in Karaikal',
    excerpt: 'An overview of the upcoming medical node expansions and the synchronization with larger JIPMER protocols...',
    author: 'Admin Central',
    authorHospital: 'District Health Command',
    date: '18 Mar 2026',
    readTime: '6 min read',
    category: 'Karaikal News',
    image: '/assets/vaccine_pro.png'
  },
  {
    id: 'blog-5',
    slug: 'pediatric-vaccination-schedule',
    title: 'Newborn Node: Vaccination Timing Protocols',
    excerpt: 'Ensuring your latest human node addition is correctly protected against environmental architecture threats...',
    author: 'Dr. M. Meena Krishnan',
    authorHospital: 'Child Care Hospital, Karaikal',
    date: '15 Mar 2026',
    readTime: '7 min read',
    category: 'COVID',
    image: '/assets/medicine_default.png'
  }
];
